/**
 * Static product catalog — used as fallback when the database is unavailable.
 * Mirrors the seed-pixieset-store.ts data so the shop page renders in dev
 * without requiring a PostgreSQL connection.
 */

const J = JSON.stringify;

export type StaticProduct = {
  id: string;
  productKey: string;
  name: string;
  description: string;
  category: string;
  subcategory: string | null;
  sizes: string | null;
  defaultSize: string | null;
  options: string | null;
  defaultOption: string | null;
  papers: string | null;
  frames: string | null;
  finishes: string | null;
  costPrice: number;
  retailPrice: number;
  fulfillmentType: string;
  labName: string | null;
  mockupUrl: string | null;
  hasRoomPreview: boolean;
  hasPersonalizedPreview: boolean;
  isDigital: boolean;
  isActive: boolean;
  isFeatured: boolean;
  comingSoon: boolean;
  sortOrder: number;
  turnaround: string | null;
};

let _id = 0;
function sid(): string {
  return `static_${++_id}`;
}

export const STATIC_PRODUCTS: StaticProduct[] = [
  // ── PRINTS ────────────────────────────────────────────────
  {
    id: sid(), productKey: "print_lustre",
    name: "Photographic Print — Lustre",
    description: "Professional photographic print on premium lustre photo paper. Rich colors, sharp detail, subtle sheen.",
    category: "PRINTS", subcategory: "lustre",
    sizes: J([
      { name: "4×6", cost: 1.80, width: 4, height: 6 },
      { name: "5×7", cost: 2.20, width: 5, height: 7 },
      { name: "8×10", cost: 3.50, width: 8, height: 10 },
      { name: "11×14", cost: 6.50, width: 11, height: 14 },
      { name: "16×20", cost: 12, width: 16, height: 20 },
      { name: "20×30", cost: 18, width: 20, height: 30 },
      { name: "24×36", cost: 25, width: 24, height: 36 },
    ]),
    papers: J([{ name: "Lustre", costAddon: 0 }, { name: "Glossy", costAddon: 0 }, { name: "Deep Matte", costAddon: 0.50 }]),
    defaultSize: "8×10", defaultOption: null, options: null, frames: null, finishes: null,
    costPrice: 1.80, retailPrice: 5, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: true, comingSoon: false,
    sortOrder: 1, turnaround: "3-5 business days",
  },
  {
    id: sid(), productKey: "print_fineart",
    name: "Fine Art Print",
    description: "Museum-quality giclée print on archival fine art paper. 100+ year longevity.",
    category: "PRINTS", subcategory: "fine-art",
    sizes: J([
      { name: "8×10", cost: 8 }, { name: "11×14", cost: 12 },
      { name: "16×20", cost: 22 }, { name: "20×30", cost: 35 }, { name: "24×36", cost: 45 },
    ]),
    papers: J([{ name: "Smooth Cotton Rag", costAddon: 0 }, { name: "Textured Fine Art", costAddon: 2 }, { name: "Baryta", costAddon: 3 }]),
    defaultSize: "8×10", defaultOption: null, options: null, frames: null, finishes: null,
    costPrice: 8, retailPrice: 22, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: true, comingSoon: false,
    sortOrder: 4, turnaround: "5-7 business days",
  },

  // ── WALL ART ──────────────────────────────────────────────
  {
    id: sid(), productKey: "wall_canvas",
    name: "Canvas Wrap",
    description: "Premium canvas hand-stretched on wooden frame. Ready to hang. Gallery-quality.",
    category: "WALL_ART", subcategory: "canvas",
    sizes: J([
      { name: "8×10", cost: 20 }, { name: "11×14", cost: 28 },
      { name: "16×20", cost: 42 }, { name: "20×30", cost: 58 },
      { name: "24×36", cost: 72 }, { name: "30×40", cost: 95 },
    ]),
    options: J([{ name: "Image Wrap", costAddon: 0 }, { name: "Mirror Wrap", costAddon: 0 }, { name: "Black Edge", costAddon: 0 }, { name: "White Edge", costAddon: 0 }]),
    defaultSize: "16×20", defaultOption: "Image Wrap",
    papers: null, frames: null, finishes: null,
    costPrice: 18, retailPrice: 45, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: true, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: true, comingSoon: false,
    sortOrder: 10, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "wall_framed_canvas",
    name: "Framed Canvas",
    description: "Canvas print in a premium floating frame. Statement wall art for any room.",
    category: "WALL_ART", subcategory: "framed-canvas",
    sizes: J([
      { name: "8×10", cost: 35 }, { name: "11×14", cost: 45 },
      { name: "16×20", cost: 65 }, { name: "20×30", cost: 85 }, { name: "24×36", cost: 110 },
    ]),
    frames: J([{ name: "Black", costAddon: 0 }, { name: "White", costAddon: 0 }, { name: "Natural Wood", costAddon: 5 }, { name: "Walnut", costAddon: 8 }]),
    defaultSize: "16×20", defaultOption: null, options: null, papers: null, finishes: null,
    costPrice: 35, retailPrice: 85, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: true, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 11, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "wall_metal",
    name: "Metal Print",
    description: "Photo on premium aluminum via dye sublimation. Ultra-vivid colors, modern look.",
    category: "WALL_ART", subcategory: "metal",
    sizes: J([
      { name: "8×10", cost: 28 }, { name: "11×14", cost: 38 },
      { name: "16×20", cost: 55 }, { name: "20×30", cost: 78 }, { name: "24×36", cost: 105 },
    ]),
    finishes: J([{ name: "High Gloss" }, { name: "Satin Matte" }]),
    defaultSize: "16×20", defaultOption: null, options: null, papers: null, frames: null,
    costPrice: 25, retailPrice: 65, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: true, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: true, comingSoon: false,
    sortOrder: 12, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "wall_acrylic",
    name: "Acrylic Print",
    description: "Photo face-mounted behind crystal-clear acrylic glass. Stunning depth and vibrancy.",
    category: "WALL_ART", subcategory: "acrylic",
    sizes: J([
      { name: "8×10", cost: 35 }, { name: "11×14", cost: 48 },
      { name: "16×20", cost: 68 }, { name: "20×30", cost: 95 }, { name: "24×36", cost: 130 },
    ]),
    defaultSize: "16×20", defaultOption: null, options: null, papers: null, frames: null, finishes: null,
    costPrice: 30, retailPrice: 75, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: true, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 13, turnaround: "7-10 business days",
  },
  {
    id: sid(), productKey: "wall_framed_print",
    name: "Framed Print",
    description: "Professional print in a handcrafted frame with acrylic glazing. Ready to hang.",
    category: "WALL_ART", subcategory: "framed-print",
    sizes: J([
      { name: "8×10", cost: 28 }, { name: "11×14", cost: 38 },
      { name: "16×20", cost: 55 }, { name: "20×30", cost: 75 }, { name: "24×36", cost: 98 },
    ]),
    frames: J([
      { name: "Classic Black", costAddon: 0 }, { name: "Classic White", costAddon: 0 },
      { name: "Natural Oak", costAddon: 5 }, { name: "Walnut", costAddon: 8 },
      { name: "Distressed Black", costAddon: 3 }, { name: "Distressed White", costAddon: 3 },
    ]),
    options: J([{ name: "White Mat", costAddon: 0 }, { name: "Black Mat", costAddon: 0 }, { name: "No Mat", costAddon: 0 }]),
    defaultSize: "11×14", defaultOption: "White Mat", papers: null, finishes: null,
    costPrice: 28, retailPrice: 68, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: true, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: true, comingSoon: false,
    sortOrder: 15, turnaround: "5-7 business days",
  },

  // ── ALBUMS ────────────────────────────────────────────────
  {
    id: sid(), productKey: "album_hardcover",
    name: "Hardcover Photo Book",
    description: "Premium hardcover photo book with matte or glossy pages. Coffee table worthy.",
    category: "ALBUMS", subcategory: "hardcover",
    sizes: J([{ name: "8×8", cost: 28 }, { name: "8×11", cost: 35 }, { name: "12×12", cost: 42 }]),
    defaultSize: "8×11", defaultOption: null, options: null, papers: null, frames: null, finishes: null,
    costPrice: 28, retailPrice: 69, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: true, comingSoon: false,
    sortOrder: 23, turnaround: "7-10 business days",
  },
  {
    id: sid(), productKey: "album_softcover",
    name: "Softcover Photo Book",
    description: "Beautiful softcover photo book with professional printing. Affordable gift option.",
    category: "ALBUMS", subcategory: "softcover",
    sizes: J([{ name: "8×8", cost: 18 }, { name: "8×11", cost: 22 }]),
    defaultSize: "8×8", defaultOption: null, options: null, papers: null, frames: null, finishes: null,
    costPrice: 18, retailPrice: 39, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 22, turnaround: "7-10 business days",
  },

  // ── CARDS ─────────────────────────────────────────────────
  {
    id: sid(), productKey: "card_flat",
    name: "Flat Greeting Card",
    description: "Single-sided flat card. Perfect for thank-you notes, holiday greetings, announcements.",
    category: "CARDS", subcategory: "flat",
    sizes: J([{ name: "4×6", cost: 1.20 }, { name: "5×7", cost: 1.80 }]),
    finishes: J([{ name: "Matte" }, { name: "Glossy" }, { name: "Pearl" }]),
    defaultSize: "5×7", defaultOption: null, options: null, papers: null, frames: null,
    costPrice: 1.20, retailPrice: 3.50, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 30, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "card_folded",
    name: "Folded Greeting Card",
    description: "Folded card with photo on front, custom message inside. Includes envelope.",
    category: "CARDS", subcategory: "folded",
    sizes: J([{ name: "5×7", cost: 2.50 }]),
    defaultSize: "5×7", defaultOption: null, options: null, papers: null, frames: null, finishes: null,
    costPrice: 2.50, retailPrice: 5.50, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 31, turnaround: "5-7 business days",
  },

  // ── DIGITAL ───────────────────────────────────────────────
  {
    id: sid(), productKey: "digital_single",
    name: "Single Photo Download",
    description: "Download a single high-resolution digital photo. Instant delivery.",
    category: "DIGITAL", subcategory: null,
    sizes: null,
    options: J([{ name: "Web-size (2048px)", costAddon: 0 }, { name: "Full Resolution", costAddon: 2 }]),
    defaultSize: null, defaultOption: "Web-size (2048px)",
    papers: null, frames: null, finishes: null,
    costPrice: 0, retailPrice: 5, fulfillmentType: "DIGITAL", labName: null,
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: false,
    isDigital: true, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 40, turnaround: "Instant",
  },
  {
    id: sid(), productKey: "digital_gallery",
    name: "Full Gallery Download",
    description: "Download all photos from this gallery. Instant delivery to your device.",
    category: "DIGITAL", subcategory: null,
    sizes: null,
    options: J([{ name: "Web-size (all photos)", costAddon: 0 }, { name: "Full Resolution (all photos)", costAddon: 10 }]),
    defaultSize: null, defaultOption: "Web-size (all photos)",
    papers: null, frames: null, finishes: null,
    costPrice: 0, retailPrice: 49, fulfillmentType: "DIGITAL", labName: null,
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: false,
    isDigital: true, isActive: true, isFeatured: true, comingSoon: false,
    sortOrder: 41, turnaround: "Instant",
  },

  // ── PACKAGES ──────────────────────────────────────────────
  {
    id: sid(), productKey: "pkg_wallart",
    name: "Wall Art Package",
    description: "1 Canvas 16×20 + 2 Framed Prints 8×10 + Full Gallery Download.",
    category: "PACKAGES", subcategory: null,
    sizes: null, defaultSize: null, defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 65, retailPrice: 179, fulfillmentType: "AUTO", labName: null,
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: false,
    isDigital: false, isActive: true, isFeatured: true, comingSoon: false,
    sortOrder: 51, turnaround: "7-10 business days",
  },
  {
    id: sid(), productKey: "pkg_premium",
    name: "Premium Package",
    description: "Metal Print 16×20 + Canvas 11×14 + 2 Framed Prints 8×10 + Full Gallery Download.",
    category: "PACKAGES", subcategory: null,
    sizes: null, defaultSize: null, defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 130, retailPrice: 349, fulfillmentType: "AUTO", labName: null,
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: false,
    isDigital: false, isActive: true, isFeatured: true, comingSoon: false,
    sortOrder: 53, turnaround: "7-10 business days",
  },

  // ── GIFTS ─────────────────────────────────────────────────
  {
    id: sid(), productKey: "gift_mug_11oz",
    name: "Photo Mug — 11oz",
    description: "Classic ceramic mug with your photo wrapped around it. Dishwasher safe.",
    category: "GIFTS", subcategory: "mug",
    sizes: null, defaultSize: null, defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 6, retailPrice: 15, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 62, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "gift_puzzle_120",
    name: "Jigsaw Puzzle — 120 pieces",
    description: "Turn your photo into a fun puzzle. 120 pieces — great for kids and families.",
    category: "GIFTS", subcategory: "puzzle",
    sizes: null, defaultSize: null, defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 12, retailPrice: 25, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: true, comingSoon: false,
    sortOrder: 69, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "gift_magnet",
    name: "Photo Magnet",
    description: "Durable fridge magnet with your favorite photo. Small but mighty.",
    category: "GIFTS", subcategory: "magnet",
    sizes: J([{ name: "2×3", cost: 3.50 }, { name: "3×4", cost: 4.50 }, { name: "4×6", cost: 6 }]),
    defaultSize: "3×4", defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 3.50, retailPrice: 8, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 60, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "gift_phone_case",
    name: "Phone Case",
    description: "Custom phone case with your photo. iPhone and Samsung available.",
    category: "GIFTS", subcategory: "phone-case",
    sizes: null, defaultSize: null, defaultOption: null,
    options: J([{ name: "Snap Case", costAddon: 0 }, { name: "Tough Case", costAddon: 4 }]),
    papers: null, frames: null, finishes: null,
    costPrice: 10, retailPrice: 22, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 72, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "gift_tote",
    name: "Tote Bag",
    description: "Sturdy canvas tote bag with your photo printed on one side.",
    category: "GIFTS", subcategory: "tote",
    sizes: null, defaultSize: null, defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 8, retailPrice: 18, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 73, turnaround: "5-7 business days",
  },

  // ── WALL ART (additional — matching WHCC/Pixieset catalog) ──
  {
    id: sid(), productKey: "wall_wood",
    name: "Wood Print",
    description: "Photo printed directly on natural birch wood. Grain shows through lighter areas for a warm, organic look.",
    category: "WALL_ART", subcategory: "wood",
    sizes: J([
      { name: "8×8", cost: 22 }, { name: "8×10", cost: 25 },
      { name: "11×14", cost: 35 }, { name: "16×20", cost: 50 },
    ]),
    defaultSize: "11×14", defaultOption: null, options: null, papers: null, frames: null, finishes: null,
    costPrice: 22, retailPrice: 55, fulfillmentType: "AUTO", labName: "WHCC",
    mockupUrl: null, hasRoomPreview: true, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 14, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "wall_bamboo",
    name: "Bamboo Panel",
    description: "Eco-friendly bamboo panel with vibrant dye-sublimation printing. Sustainable and stunning.",
    category: "WALL_ART", subcategory: "bamboo",
    sizes: J([
      { name: "8×8", cost: 28 }, { name: "8×10", cost: 32 },
      { name: "11×14", cost: 42 }, { name: "16×20", cost: 58 },
    ]),
    defaultSize: "11×14", defaultOption: null, options: null, papers: null, frames: null, finishes: null,
    costPrice: 28, retailPrice: 65, fulfillmentType: "AUTO", labName: "WHCC",
    mockupUrl: null, hasRoomPreview: true, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 15, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "wall_standout",
    name: "Standout Mount",
    description: "Photo print mounted on thick foam with beveled edges. Modern frameless display, ready to hang.",
    category: "WALL_ART", subcategory: "standout",
    sizes: J([
      { name: "8×10", cost: 18 }, { name: "11×14", cost: 28 },
      { name: "16×20", cost: 40 }, { name: "20×30", cost: 60 },
    ]),
    finishes: J([{ name: "Lustre" }, { name: "Glossy" }, { name: "Matte" }]),
    defaultSize: "11×14", defaultOption: null, options: null, papers: null, frames: null,
    costPrice: 18, retailPrice: 42, fulfillmentType: "AUTO", labName: "WHCC",
    mockupUrl: null, hasRoomPreview: true, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 16, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "wall_float_wrap",
    name: "Float Wrap",
    description: "Photo on metal with a unique recessed float mount. Appears to hover off the wall.",
    category: "WALL_ART", subcategory: "float-wrap",
    sizes: J([
      { name: "8×10", cost: 35 }, { name: "11×14", cost: 48 },
      { name: "16×20", cost: 65 }, { name: "20×30", cost: 90 },
    ]),
    defaultSize: "16×20", defaultOption: null, options: null, papers: null, frames: null, finishes: null,
    costPrice: 35, retailPrice: 78, fulfillmentType: "AUTO", labName: "WHCC",
    mockupUrl: null, hasRoomPreview: true, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 17, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "wall_float_frame",
    name: "Float Frame",
    description: "Print suspended inside a frame with a visible gap. Gallery-style floating effect.",
    category: "WALL_ART", subcategory: "float-frame",
    sizes: J([
      { name: "8×10", cost: 45 }, { name: "11×14", cost: 58 },
      { name: "16×20", cost: 78 }, { name: "20×30", cost: 105 },
    ]),
    frames: J([
      { name: "Black", costAddon: 0 }, { name: "White", costAddon: 0 },
      { name: "Natural Wood", costAddon: 5 }, { name: "Walnut", costAddon: 8 },
    ]),
    defaultSize: "11×14", defaultOption: null, options: null, papers: null, finishes: null,
    costPrice: 45, retailPrice: 110, fulfillmentType: "AUTO", labName: "WHCC",
    mockupUrl: null, hasRoomPreview: true, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 18, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "wall_photo_tiles",
    name: "Photo Tiles",
    description: "Lightweight adhesive tiles. Stick, peel, and rearrange anytime. No nails needed.",
    category: "WALL_ART", subcategory: "tiles",
    sizes: J([{ name: "8×8", cost: 12 }, { name: "8×10", cost: 14 }]),
    defaultSize: "8×8", defaultOption: null, options: null, papers: null, frames: null, finishes: null,
    costPrice: 12, retailPrice: 28, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: true, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 19, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "wall_gallery_set",
    name: "Gallery Wall Set",
    description: "Curated set of 3-5 coordinated prints designed to hang as a gallery wall. Includes layout template.",
    category: "WALL_ART", subcategory: "gallery-set",
    sizes: J([
      { name: "3-piece set (8×10)", cost: 65 },
      { name: "5-piece set (mixed)", cost: 120 },
    ]),
    defaultSize: "3-piece set (8×10)", defaultOption: null, options: null, papers: null,
    frames: J([{ name: "Black", costAddon: 0 }, { name: "White", costAddon: 0 }, { name: "Natural Wood", costAddon: 10 }]),
    finishes: null,
    costPrice: 65, retailPrice: 149, fulfillmentType: "AUTO", labName: "WHCC",
    mockupUrl: null, hasRoomPreview: true, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: true, comingSoon: false,
    sortOrder: 20, turnaround: "7-10 business days",
  },

  // ── ALBUMS (additional) ───────────────────────────────────
  {
    id: sid(), productKey: "album_layflat",
    name: "Layflat Album",
    description: "Premium layflat binding with seamless panoramic spreads. Pages lie perfectly flat.",
    category: "ALBUMS", subcategory: "layflat",
    sizes: J([{ name: "8×8", cost: 80 }, { name: "10×10", cost: 110 }, { name: "12×12", cost: 145 }]),
    defaultSize: "10×10", defaultOption: null,
    options: J([{ name: "Premium Leather", costAddon: 0 }, { name: "Linen", costAddon: 0 }, { name: "Silk", costAddon: 10 }, { name: "Acrylic Cover", costAddon: 20 }]),
    papers: null, frames: null, finishes: null,
    costPrice: 80, retailPrice: 220, fulfillmentType: "MANUAL", labName: "WHCC",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: true, comingSoon: false,
    sortOrder: 24, turnaround: "10-14 business days",
  },
  {
    id: sid(), productKey: "album_accordion",
    name: "Accordion Mini Album",
    description: "Adorable accordion-fold mini album. Fits in a purse — perfect surprise gift.",
    category: "ALBUMS", subcategory: "accordion",
    sizes: J([{ name: "3×3 (10 panels)", cost: 15 }, { name: "4×4 (8 panels)", cost: 18 }]),
    defaultSize: "3×3 (10 panels)", defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 15, retailPrice: 35, fulfillmentType: "MANUAL", labName: "WHCC",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 25, turnaround: "7-10 business days",
  },

  // ── CARDS (additional) ────────────────────────────────────
  {
    id: sid(), productKey: "card_postcard",
    name: "Postcard",
    description: "Classic 4×6 or 5×7 postcard with your photo on front. Great for marketing or thank-you notes.",
    category: "CARDS", subcategory: "postcard",
    sizes: J([{ name: "4×6", cost: 1.20 }, { name: "5×7", cost: 1.80 }]),
    defaultSize: "5×7", defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 1.20, retailPrice: 2.50, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 32, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "card_holiday",
    name: "Holiday Card",
    description: "Personalized holiday card with your photo and custom text. Includes envelope.",
    category: "CARDS", subcategory: "holiday",
    sizes: J([{ name: "5×7", cost: 2.50 }]),
    defaultSize: "5×7", defaultOption: null,
    options: null, papers: null, frames: null,
    finishes: J([{ name: "Matte" }, { name: "Glossy" }, { name: "Pearl" }]),
    costPrice: 2.50, retailPrice: 5, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 33, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "card_save_date",
    name: "Save the Date",
    description: "Announce your wedding date with a beautiful personalized card.",
    category: "CARDS", subcategory: "save-the-date",
    sizes: J([{ name: "5×7", cost: 2.50 }, { name: "4×6", cost: 1.80 }]),
    defaultSize: "5×7", defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 1.80, retailPrice: 4.50, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 34, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "card_thankyou",
    name: "Thank You Card",
    description: "Express gratitude with a personalized thank-you card featuring your photo.",
    category: "CARDS", subcategory: "thank-you",
    sizes: J([{ name: "5×7", cost: 2.50 }]),
    defaultSize: "5×7", defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 2.50, retailPrice: 5, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 35, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "card_business",
    name: "Business Card",
    description: "Professional business cards featuring your photography. 50-card minimum.",
    category: "CARDS", subcategory: "business",
    sizes: J([{ name: "3.5×2 (50 cards)", cost: 15 }, { name: "3.5×2 (100 cards)", cost: 22 }]),
    defaultSize: "3.5×2 (50 cards)", defaultOption: null,
    options: null, papers: null, frames: null,
    finishes: J([{ name: "Matte" }, { name: "Glossy" }, { name: "Linen" }]),
    costPrice: 15, retailPrice: 29, fulfillmentType: "AUTO", labName: "WHCC",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 36, turnaround: "5-7 business days",
  },

  // ── GIFTS (additional — matching WHCC keepsakes + ornaments) ─
  {
    id: sid(), productKey: "gift_mug_15oz",
    name: "Photo Mug — 15oz",
    description: "Oversized ceramic mug for those who need more coffee (and more photo).",
    category: "GIFTS", subcategory: "mug",
    sizes: null, defaultSize: null, defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 7, retailPrice: 18, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 63, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "gift_enamel_mug",
    name: "Enamel Mug",
    description: "Vintage-style enamel mug with your photo. Perfect for camping and outdoor lovers.",
    category: "GIFTS", subcategory: "mug",
    sizes: null, defaultSize: null, defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 8, retailPrice: 18, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 64, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "gift_keychain",
    name: "Photo Keychain",
    description: "Carry your favorite memory everywhere. Durable acrylic keychain.",
    category: "GIFTS", subcategory: "keychain",
    sizes: J([{ name: "Rectangle", cost: 5 }, { name: "Circle", cost: 5 }]),
    defaultSize: "Rectangle", defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 5, retailPrice: 12, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 65, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "gift_water_bottle",
    name: "Water Bottle",
    description: "Stainless steel water bottle with your photo. Keeps drinks cold 24h or hot 12h.",
    category: "GIFTS", subcategory: "water-bottle",
    sizes: J([{ name: "17oz", cost: 12 }, { name: "25oz", cost: 16 }]),
    defaultSize: "17oz", defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 12, retailPrice: 28, fulfillmentType: "AUTO", labName: "PRINTFUL",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 66, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "gift_ornament_circle",
    name: "Ceramic Ornament — Circle",
    description: "Personalized ceramic ornament with ribbon. Perfect holiday keepsake.",
    category: "GIFTS", subcategory: "ornament",
    sizes: null, defaultSize: null, defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 5, retailPrice: 12, fulfillmentType: "AUTO", labName: "WHCC",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 67, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "gift_ornament_heart",
    name: "Ceramic Ornament — Heart",
    description: "Heart-shaped ceramic ornament. Show your love on the tree.",
    category: "GIFTS", subcategory: "ornament",
    sizes: null, defaultSize: null, defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 5, retailPrice: 12, fulfillmentType: "AUTO", labName: "WHCC",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 68, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "gift_coasters",
    name: "Photo Coasters (Set of 4)",
    description: "Set of 4 hardboard coasters with cork backing. Each features a different photo.",
    category: "GIFTS", subcategory: "coaster",
    sizes: null, defaultSize: null, defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 10, retailPrice: 22, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 70, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "gift_cushion",
    name: "Cushion Cover",
    description: "Soft cushion cover with your photo. Insert not included.",
    category: "GIFTS", subcategory: "cushion",
    sizes: J([{ name: "16×16", cost: 12 }, { name: "18×18", cost: 15 }]),
    defaultSize: "16×16", defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 12, retailPrice: 28, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 74, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "gift_blanket",
    name: "Photo Blanket",
    description: "Cozy photo blanket — your favorite memory keeps you warm.",
    category: "GIFTS", subcategory: "blanket",
    sizes: J([{ name: "50×60 Fleece", cost: 28 }, { name: "60×80 Sherpa", cost: 38 }]),
    defaultSize: "50×60 Fleece", defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 28, retailPrice: 55, fulfillmentType: "AUTO", labName: "PRINTFUL",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 75, turnaround: "7-10 business days",
  },
  {
    id: sid(), productKey: "gift_puzzle_500",
    name: "Jigsaw Puzzle — 500 pieces",
    description: "Challenging 500-piece puzzle from your favorite photo. Hours of family fun.",
    category: "GIFTS", subcategory: "puzzle",
    sizes: null, defaultSize: null, defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 18, retailPrice: 38, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 71, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "gift_mousepad",
    name: "Mouse Pad",
    description: "Custom photo mouse pad with anti-slip rubber base.",
    category: "GIFTS", subcategory: "mousepad",
    sizes: J([{ name: "Standard", cost: 6 }, { name: "Large", cost: 9 }]),
    defaultSize: "Standard", defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 6, retailPrice: 14, fulfillmentType: "AUTO", labName: "PRODIGI",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 76, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "gift_card_25",
    name: "Gift Card — €25",
    description: "Let them choose their own products. Gift card never expires.",
    category: "GIFTS", subcategory: "gift-card",
    sizes: null, defaultSize: null, defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 0, retailPrice: 25, fulfillmentType: "DIGITAL", labName: null,
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: false,
    isDigital: true, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 77, turnaround: "Instant",
  },
  {
    id: sid(), productKey: "gift_card_50",
    name: "Gift Card — €50",
    description: "Let them choose their own products. Gift card never expires.",
    category: "GIFTS", subcategory: "gift-card",
    sizes: null, defaultSize: null, defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 0, retailPrice: 50, fulfillmentType: "DIGITAL", labName: null,
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: false,
    isDigital: true, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 78, turnaround: "Instant",
  },
  {
    id: sid(), productKey: "gift_card_100",
    name: "Gift Card — €100",
    description: "Let them choose their own products. Gift card never expires.",
    category: "GIFTS", subcategory: "gift-card",
    sizes: null, defaultSize: null, defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 0, retailPrice: 100, fulfillmentType: "DIGITAL", labName: null,
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: false,
    isDigital: true, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 79, turnaround: "Instant",
  },

  // ── TABLETOP DISPLAYS ─────────────────────────────────────
  {
    id: sid(), productKey: "tabletop_acrylic_block",
    name: "Acrylic Block",
    description: "Crystal-clear freestanding acrylic block. Perfect desk or shelf display.",
    category: "GIFTS", subcategory: "acrylic-block",
    sizes: J([{ name: "4×4", cost: 15 }, { name: "4×6", cost: 18 }, { name: "5×7", cost: 22 }]),
    defaultSize: "4×6", defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 15, retailPrice: 35, fulfillmentType: "AUTO", labName: "WHCC",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 80, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "tabletop_bamboo_block",
    name: "Bamboo Mini Block",
    description: "Natural bamboo desktop display. Warm, eco-friendly accent for any desk or shelf.",
    category: "GIFTS", subcategory: "bamboo-block",
    sizes: J([{ name: "4×4", cost: 12 }, { name: "4×6", cost: 15 }]),
    defaultSize: "4×4", defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 12, retailPrice: 28, fulfillmentType: "AUTO", labName: "WHCC",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 81, turnaround: "5-7 business days",
  },
  {
    id: sid(), productKey: "tabletop_framed",
    name: "Framed Tabletop Print",
    description: "Small framed print with easel back. Perfect for desks, shelves, and nightstands.",
    category: "GIFTS", subcategory: "tabletop-frame",
    sizes: J([{ name: "4×6", cost: 12 }, { name: "5×7", cost: 16 }]),
    frames: J([{ name: "Black", costAddon: 0 }, { name: "White", costAddon: 0 }, { name: "Gold", costAddon: 3 }]),
    defaultSize: "5×7", defaultOption: null, options: null, papers: null, finishes: null,
    costPrice: 12, retailPrice: 25, fulfillmentType: "AUTO", labName: "WHCC",
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: true,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 82, turnaround: "5-7 business days",
  },

  // ── OTHERS ────────────────────────────────────────────────
  {
    id: sid(), productKey: "other_video_reel",
    name: "Video Reel",
    description: "AI-generated video reel from your best photos with music and transitions.",
    category: "OTHERS", subcategory: null,
    sizes: null, defaultSize: null, defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 0, retailPrice: 10, fulfillmentType: "DIGITAL", labName: null,
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: false,
    isDigital: true, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 90, turnaround: "Instant",
  },
  {
    id: sid(), productKey: "other_retouching",
    name: "Professional Retouching",
    description: "Professional color correction, skin smoothing, and blemish removal per photo.",
    category: "OTHERS", subcategory: null,
    sizes: null, defaultSize: null, defaultOption: null,
    options: null, papers: null, frames: null, finishes: null,
    costPrice: 3, retailPrice: 12, fulfillmentType: "MANUAL", labName: null,
    mockupUrl: null, hasRoomPreview: false, hasPersonalizedPreview: false,
    isDigital: false, isActive: true, isFeatured: false, comingSoon: false,
    sortOrder: 91, turnaround: "2-3 business days",
  },
];
