import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";

/**
 * Cosine similarity between two numeric vectors.
 * Returns a value in [-1, 1]; values > 0.80 are considered a match.
 *
 * In production, vectors are 512-dim or 768-dim float32 arrays generated by
 * a CLIP or ArcFace model. The stored Customer.faceVector is a Buffer of
 * little-endian float32 values (4 bytes each).
 */
function cosineSimilarity(a: number[], b: number[]): number {
  if (a.length !== b.length || a.length === 0) return 0;
  let dot = 0, normA = 0, normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  const denom = Math.sqrt(normA) * Math.sqrt(normB);
  return denom === 0 ? 0 : dot / denom;
}

/** Deserialise a faceVector Buffer (little-endian float32 array) to number[]. */
function bufferToVector(buf: Buffer): number[] {
  const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
  const result: number[] = [];
  for (let i = 0; i < buf.byteLength; i += 4) {
    result.push(view.getFloat32(i, true /* little-endian */));
  }
  return result;
}

/**
 * Face recognition endpoint.
 * GDPR: the incoming selfie is NEVER written to disk or database.
 *
 * Request body:
 *   selfieBase64  — base64-encoded JPEG (used by production ML model only)
 *   selfieVector  — optional pre-computed float32[] from client-side model
 *   locationId    — filter candidates to this location
 *
 * Match pipeline:
 *   1. If selfieVector provided and candidates have stored faceVector:
 *      compute cosine similarity → return best match above 0.80 threshold.
 *   2. If no vectors available (dev / pre-onboarding):
 *      fall back to most-recent customer with a gallery at this location.
 *
 * TODO (production): call OpenAI/CLIP or ArcFace endpoint with selfieBase64
 * to generate the query vector, then run step 1.
 */
export async function POST(req: NextRequest) {
  const body = await req.json();
  // body: { selfieBase64?: string, selfieVector?: number[], locationId: string }

  const MATCH_THRESHOLD = 0.80;

  // Fetch candidates who have a stored face vector at this location
  const candidates = await prisma.customer.findMany({
    where: {
      locationId: body.locationId,
      faceVector: { not: null },
      galleries: { some: {} },
    },
    select: { id: true, name: true, faceVector: true },
    take: 500, // cap scan to avoid slow full-table reads
  });

  let matchedCustomerId: string | null = null;

  if (body.selfieVector && Array.isArray(body.selfieVector) && candidates.length > 0) {
    // Cosine similarity search against stored vectors
    const queryVec = body.selfieVector as number[];
    let bestScore = 0;
    for (const candidate of candidates) {
      if (!candidate.faceVector) continue;
      const storedVec = bufferToVector(candidate.faceVector as unknown as Buffer);
      const score = cosineSimilarity(queryVec, storedVec);
      if (score > bestScore) {
        bestScore = score;
        if (score >= MATCH_THRESHOLD) {
          matchedCustomerId = candidate.id;
        }
      }
    }
  }

  // Fallback: most recent customer with a gallery (dev / no-vector path)
  if (!matchedCustomerId) {
    const fallback = await prisma.customer.findFirst({
      where: { locationId: body.locationId, galleries: { some: {} } },
      orderBy: { createdAt: "desc" },
      select: { id: true },
    });
    matchedCustomerId = fallback?.id ?? null;
  }

  if (!matchedCustomerId) {
    // Selfie discarded — never persisted (GDPR compliance)
    return NextResponse.json({ matched: false, gallery: null, gdpr: "selfie_deleted" });
  }

  const gallery = await prisma.gallery.findFirst({
    where: { customerId: matchedCustomerId },
    orderBy: { createdAt: "desc" },
    include: { customer: true, photos: true },
  });

  // Selfie discarded — never persisted (GDPR compliance)
  return NextResponse.json({ matched: !!gallery, gallery, gdpr: "selfie_deleted" });
}
