import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const ADD_ONS = [
  { name: "Extra 30 minutes", description: "Extend your session by half an hour", price: 35, sortOrder: 0 },
  { name: "Outfit change", description: "Extra location stop for a wardrobe swap", price: 25, sortOrder: 1 },
  { name: "Rush delivery (6h)", description: "Get your edited photos within 6 hours", price: 29, sortOrder: 2 },
  { name: "Full unedited gallery", description: "Receive every shot from the session, unedited", price: 49, sortOrder: 3 },
  { name: "Print pack (5 prints 8x10)", description: "Five premium 8\u00d710 inch prints shipped to you", price: 39, sortOrder: 4 },
  { name: "Photo album (20 pages)", description: "Hardcover lay-flat album with 20 pages", price: 79, sortOrder: 5 },
  { name: "Canvas print 40x60cm", description: "Gallery-wrapped canvas, ready to hang", price: 65, sortOrder: 6 },
  { name: "Digital pass (unlimited access)", description: "Unlimited gallery access, no expiry", price: 49, sortOrder: 7 },
  { name: "AI video reel (15s)", description: "Slideshow reel with music, ready for social media", price: 19, sortOrder: 8 },
  { name: "5 Magic Shot overlays", description: "Five photos with 3D character or AR overlays", price: 25, sortOrder: 9 },
];

interface PackageSeed {
  name: string;
  slug: string;
  description: string;
  shortDescription: string;
  category: "FAMILY" | "COUPLE" | "SOLO" | "GROUP" | "KIDS" | "EVENT" | "SPECIALTY";
  sessionType: string;
  duration: number;
  deliveredPhotos: number;
  price: number;
  depositAmount: number | null;
  maxGroupSize: number;
  isFeatured: boolean;
  sortOrder: number;
  whatsIncluded: string[];
  whatToBring: string[];
  cancellationPolicy: string;
}

const PACKAGES: PackageSeed[] = [
  // ── FAMILY ──
  {
    name: "Family Beach Mini Session",
    slug: "family-beach-mini",
    description: "A quick, fun session at golden hour. Perfect for families with young kids who want beautiful photos without the long commitment. We capture candid and posed moments on the beach in 30 relaxed minutes.",
    shortDescription: "Quick and fun! Perfect for families with young kids.",
    category: "FAMILY",
    sessionType: "MIXED",
    duration: 30,
    deliveredPhotos: 15,
    price: 49,
    depositAmount: null,
    maxGroupSize: 6,
    isFeatured: false,
    sortOrder: 1,
    whatsIncluded: ["15+ edited photos", "Online gallery with downloads", "WhatsApp delivery within 24h", "1 free digital download"],
    whatToBring: ["Comfortable clothing in coordinating colours", "Sunscreen", "Snacks for little ones", "A sense of adventure!"],
    cancellationPolicy: "Free cancellation up to 24 hours before. 50% refund within 24 hours. No refund for no-shows.",
  },
  {
    name: "Family Beach Session",
    slug: "family-beach-session",
    description: "Our most popular family package. One hour of relaxed shooting at the beach during golden hour. We mix natural candid moments with beautifully posed group shots. Outfit changes welcome.",
    shortDescription: "Our most popular family session. Relaxed vibes at golden hour.",
    category: "FAMILY",
    sessionType: "MIXED",
    duration: 60,
    deliveredPhotos: 30,
    price: 79,
    depositAmount: 25,
    maxGroupSize: 8,
    isFeatured: true,
    sortOrder: 2,
    whatsIncluded: ["30+ edited photos", "Online gallery with downloads", "WhatsApp delivery within 24h", "1 free 8x10 print", "Outfit change included"],
    whatToBring: ["Two coordinating outfits", "Props (hats, sunglasses, toys)", "Comfortable shoes for walking on sand"],
    cancellationPolicy: "Free cancellation up to 24 hours before. 50% refund within 24 hours. No refund for no-shows.",
  },
  {
    name: "Family Resort Experience",
    slug: "family-resort-experience",
    description: "A full resort experience covering pool, beach, gardens, and candid moments. 90 minutes of storytelling photography that captures your family holiday as it really feels. Multiple locations within your resort.",
    shortDescription: "Full resort experience: pool, beach, gardens, and candid moments.",
    category: "FAMILY",
    sessionType: "MIXED",
    duration: 90,
    deliveredPhotos: 50,
    price: 129,
    depositAmount: 40,
    maxGroupSize: 10,
    isFeatured: false,
    sortOrder: 3,
    whatsIncluded: ["50+ edited photos", "Online gallery", "WhatsApp + email delivery", "2 free 8x10 prints", "Multiple resort locations", "Outfit change included"],
    whatToBring: ["Swimwear + dry outfit", "Favourite holiday accessories", "Sunscreen and towels"],
    cancellationPolicy: "Free cancellation up to 48 hours before. 50% refund within 48 hours. No refund for no-shows.",
  },
  {
    name: "Family Premium Collection",
    slug: "family-premium-collection",
    description: "The ultimate family package. Two hours across multiple locations with outfit changes, golden hour guaranteed. Includes a luxury photo album and priority editing. Perfect for milestone celebrations or when you want the absolute best.",
    shortDescription: "The ultimate family package. Multiple locations, outfit changes, golden hour.",
    category: "FAMILY",
    sessionType: "MIXED",
    duration: 120,
    deliveredPhotos: 80,
    price: 199,
    depositAmount: 60,
    maxGroupSize: 12,
    isFeatured: true,
    sortOrder: 4,
    whatsIncluded: ["80+ edited photos", "20-page luxury album", "Online gallery", "All photos in full resolution", "Rush delivery (24h)", "Golden hour guaranteed", "Multiple locations + outfit changes"],
    whatToBring: ["3 coordinating outfits", "Props and accessories", "Comfortable shoes", "Snacks and water for kids"],
    cancellationPolicy: "Free cancellation up to 48 hours before. 50% refund within 48 hours. No refund for no-shows.",
  },
  // ── COUPLE ──
  {
    name: "Couple Quick Snap",
    slug: "couple-quick-snap",
    description: "A quick 30-minute portrait session for couples who want beautiful holiday photos without the time commitment. Fun, natural, and Instagram-ready.",
    shortDescription: "Quick, fun couple portraits. Instagram-ready in 30 minutes.",
    category: "COUPLE",
    sessionType: "PORTRAIT",
    duration: 30,
    deliveredPhotos: 15,
    price: 39,
    depositAmount: null,
    maxGroupSize: 2,
    isFeatured: false,
    sortOrder: 10,
    whatsIncluded: ["15+ edited photos", "Online gallery", "WhatsApp delivery within 24h"],
    whatToBring: ["Matching or coordinating outfits", "Sunglasses, hats, accessories"],
    cancellationPolicy: "Free cancellation up to 24 hours before. No refund within 24 hours.",
  },
  {
    name: "Romantic Couple Session",
    slug: "romantic-couple-session",
    description: "One hour of beautiful, intimate photography at golden hour. We guide you through natural poses that feel real, not forced. Beach, gardens, or architectural backdrops.",
    shortDescription: "Beautiful, intimate photography at golden hour.",
    category: "COUPLE",
    sessionType: "PORTRAIT",
    duration: 60,
    deliveredPhotos: 30,
    price: 69,
    depositAmount: 20,
    maxGroupSize: 2,
    isFeatured: true,
    sortOrder: 11,
    whatsIncluded: ["30+ edited photos", "Online gallery", "WhatsApp delivery within 24h", "1 free 8x10 print", "Location recommendations"],
    whatToBring: ["Two outfits (casual + dressy)", "Personal props (flowers, champagne)"],
    cancellationPolicy: "Free cancellation up to 24 hours before. 50% refund within 24 hours.",
  },
  {
    name: "Sunset Romance",
    slug: "sunset-romance",
    description: "Golden hour plus blue hour \u2014 the most romantic 90 minutes of your trip. We start in warm golden light and finish in the soft blue tones of dusk. Multiple locations for variety.",
    shortDescription: "Golden hour + blue hour. The most romantic photos of your trip.",
    category: "COUPLE",
    sessionType: "PORTRAIT",
    duration: 90,
    deliveredPhotos: 50,
    price: 119,
    depositAmount: 35,
    maxGroupSize: 2,
    isFeatured: false,
    sortOrder: 12,
    whatsIncluded: ["50+ edited photos", "Online gallery", "Rush delivery (24h)", "2 free prints", "Golden hour + blue hour", "Multiple locations"],
    whatToBring: ["Dressy outfit for sunset shots", "Casual outfit for candids", "Comfortable shoes"],
    cancellationPolicy: "Free cancellation up to 24 hours before. 50% refund within 24 hours.",
  },
  {
    name: "Honeymoon Luxe",
    slug: "honeymoon-luxe",
    description: "Celebrate your honeymoon with a cinematic two-hour experience. We create magazine-worthy photos across multiple stunning locations. Includes a luxury album and video reel.",
    shortDescription: "Celebrate your honeymoon with a cinematic photo experience.",
    category: "COUPLE",
    sessionType: "MIXED",
    duration: 120,
    deliveredPhotos: 80,
    price: 179,
    depositAmount: 55,
    maxGroupSize: 2,
    isFeatured: true,
    sortOrder: 13,
    whatsIncluded: ["80+ edited photos", "15s video reel with music", "20-page luxury album", "Online gallery", "Rush delivery", "Golden hour guaranteed", "Multiple locations"],
    whatToBring: ["3 outfits (casual, dressy, swimwear)", "Personal mementos", "Champagne for toasting shots"],
    cancellationPolicy: "Free cancellation up to 48 hours before. 50% refund within 48 hours.",
  },
  // ── SOLO / PORTRAIT ──
  {
    name: "Solo Portrait",
    slug: "solo-portrait",
    description: "Professional portrait session for solo travellers. Whether for social media, personal branding, or simply beautiful holiday memories. Relaxed, guided posing.",
    shortDescription: "Professional holiday portraits in just 30 minutes.",
    category: "SOLO",
    sessionType: "PORTRAIT",
    duration: 30,
    deliveredPhotos: 15,
    price: 35,
    depositAmount: null,
    maxGroupSize: 1,
    isFeatured: false,
    sortOrder: 20,
    whatsIncluded: ["15+ edited photos", "Online gallery", "WhatsApp delivery within 24h"],
    whatToBring: ["Your favourite outfit", "Accessories (sunglasses, hat, bag)"],
    cancellationPolicy: "Free cancellation up to 24 hours before. No refund within 24 hours.",
  },
  {
    name: "Influencer Content Pack",
    slug: "influencer-content-pack",
    description: "Instagram-ready content for creators. One hour across multiple locations with varied styles: flat lays, action, portraits, detail shots. Includes 5 vertical reels. You leave with a week of content.",
    shortDescription: "Instagram-ready content. Multiple angles, locations, and styles.",
    category: "SOLO",
    sessionType: "MIXED",
    duration: 60,
    deliveredPhotos: 30,
    price: 89,
    depositAmount: 25,
    maxGroupSize: 1,
    isFeatured: true,
    sortOrder: 21,
    whatsIncluded: ["30+ edited photos", "5 vertical video reels", "Stories-ready crops", "Online gallery", "Rush delivery (12h)", "Multiple locations and styles"],
    whatToBring: ["3\u20134 outfits for variety", "Props and accessories", "Products to feature (if any)"],
    cancellationPolicy: "Free cancellation up to 24 hours before. 50% refund within 24 hours.",
  },
  {
    name: "Professional Headshot",
    slug: "professional-headshot",
    description: "Clean, professional headshots suitable for LinkedIn, corporate bios, and personal branding. Studio-quality results in a natural setting. Retouched to perfection.",
    shortDescription: "LinkedIn-ready professional headshots in a natural setting.",
    category: "SOLO",
    sessionType: "PORTRAIT",
    duration: 30,
    deliveredPhotos: 10,
    price: 45,
    depositAmount: null,
    maxGroupSize: 1,
    isFeatured: false,
    sortOrder: 22,
    whatsIncluded: ["10 retouched headshots", "Multiple background options", "Online gallery", "Corporate-ready crops"],
    whatToBring: ["Professional attire", "Backup shirt/blazer"],
    cancellationPolicy: "Free cancellation up to 24 hours before. No refund within 24 hours.",
  },
  // ── GROUP ──
  {
    name: "Friends Getaway Session",
    slug: "friends-getaway-session",
    description: "Get the group together for an epic photo session! Fun, energetic, and candid. Perfect for friend groups on holiday, birthday trips, or reunion weekends.",
    shortDescription: "Epic group session for friends on holiday. Up to 8 people.",
    category: "GROUP",
    sessionType: "CANDID",
    duration: 60,
    deliveredPhotos: 30,
    price: 99,
    depositAmount: 30,
    maxGroupSize: 8,
    isFeatured: true,
    sortOrder: 30,
    whatsIncluded: ["30+ edited photos", "Individual + group shots", "Online gallery for everyone", "WhatsApp delivery within 24h"],
    whatToBring: ["Coordinating outfits (optional)", "Props, inflatables, silly accessories", "Good vibes!"],
    cancellationPolicy: "Free cancellation up to 24 hours before. 50% refund within 24 hours.",
  },
  {
    name: "Celebration Session",
    slug: "celebration-session",
    description: "Birthday parties, bachelor/bachelorette weekends, family reunions, or any group celebration. 90 minutes covering the event atmosphere, group shots, and individual portraits.",
    shortDescription: "Perfect for birthdays, bachelor/ettes, reunions. Up to 15 people.",
    category: "GROUP",
    sessionType: "MIXED",
    duration: 90,
    deliveredPhotos: 50,
    price: 149,
    depositAmount: 45,
    maxGroupSize: 15,
    isFeatured: false,
    sortOrder: 31,
    whatsIncluded: ["50+ edited photos", "Group + individual portraits", "Candid celebration coverage", "Online gallery for all guests", "2 free prints"],
    whatToBring: ["Party props and decorations", "Matching outfits if planned", "Cake or celebration items"],
    cancellationPolicy: "Free cancellation up to 48 hours before. 50% refund within 48 hours.",
  },
  // ── KIDS ──
  {
    name: "Kids Splash Session",
    slug: "kids-splash-session",
    description: "Action-packed water park photography! We capture the splashes, slides, and pure joy of kids in the water. Fast shutter speeds freeze every droplet.",
    shortDescription: "Action shots at the water park. Splashes, slides, and pure joy.",
    category: "KIDS",
    sessionType: "ACTION",
    duration: 30,
    deliveredPhotos: 20,
    price: 39,
    depositAmount: null,
    maxGroupSize: 4,
    isFeatured: false,
    sortOrder: 40,
    whatsIncluded: ["20+ edited action photos", "High-speed freeze-frame shots", "Online gallery", "WhatsApp delivery within 24h"],
    whatToBring: ["Swimwear and goggles", "Towels", "Favourite pool toys", "Waterproof sunscreen applied beforehand"],
    cancellationPolicy: "Free cancellation up to 24 hours before. No refund within 24 hours.",
  },
  {
    name: "Kids Adventure Session",
    slug: "kids-adventure-session",
    description: "One hour of fun portraits and action shots. We let kids be kids \u2014 running on the beach, building sandcastles, climbing trees. Natural, unforced, and authentic childhood memories.",
    shortDescription: "Let kids be kids! Natural, unforced childhood holiday memories.",
    category: "KIDS",
    sessionType: "CANDID",
    duration: 60,
    deliveredPhotos: 30,
    price: 69,
    depositAmount: 20,
    maxGroupSize: 6,
    isFeatured: true,
    sortOrder: 41,
    whatsIncluded: ["30+ edited photos", "Action + portrait mix", "Online gallery", "WhatsApp delivery", "1 free 8x10 print"],
    whatToBring: ["Play clothes + nice outfit", "Favourite toys or books", "Snacks and water", "Patience and humour!"],
    cancellationPolicy: "Free cancellation up to 24 hours before. 50% refund within 24 hours.",
  },
  // ── EVENT ──
  {
    name: "Birthday Party Coverage",
    slug: "birthday-party-coverage",
    description: "Two hours of party photography covering set-up, arrivals, cake, activities, and group shots. Professionally edited gallery delivered within 48 hours.",
    shortDescription: "Complete birthday party coverage. Cake, candles, and celebrations.",
    category: "EVENT",
    sessionType: "CANDID",
    duration: 120,
    deliveredPhotos: 100,
    price: 199,
    depositAmount: 60,
    maxGroupSize: 30,
    isFeatured: false,
    sortOrder: 50,
    whatsIncluded: ["100+ edited photos", "Event timeline coverage", "Group + candid shots", "Online gallery for all guests", "Delivery within 48h"],
    whatToBring: ["Decorations set up before session", "Guest list for group shots", "Cake and party items"],
    cancellationPolicy: "Free cancellation up to 48 hours before. 50% refund within 48 hours.",
  },
  {
    name: "Corporate Event",
    slug: "corporate-event",
    description: "Professional corporate event photography. Conferences, team-building days, product launches, or company retreats. Corporate headshots available as add-on.",
    shortDescription: "Professional coverage for corporate events and team days.",
    category: "EVENT",
    sessionType: "MIXED",
    duration: 240,
    deliveredPhotos: 200,
    price: 399,
    depositAmount: 120,
    maxGroupSize: 50,
    isFeatured: false,
    sortOrder: 51,
    whatsIncluded: ["200+ edited photos", "Full event coverage", "Team + individual portraits", "Online gallery", "Corporate-use license", "Delivery within 72h"],
    whatToBring: ["Event schedule and key moments list", "Company branding materials", "List of VIPs for priority shots"],
    cancellationPolicy: "Free cancellation up to 72 hours before. 50% refund within 72 hours.",
  },
  {
    name: "Private Event Coverage",
    slug: "private-event-coverage",
    description: "Three hours of dedicated event photography. Anniversaries, engagement parties, graduation celebrations, religious ceremonies, or milestone dinners.",
    shortDescription: "Dedicated coverage for anniversaries, graduations, and milestones.",
    category: "EVENT",
    sessionType: "CANDID",
    duration: 180,
    deliveredPhotos: 150,
    price: 299,
    depositAmount: 90,
    maxGroupSize: 40,
    isFeatured: true,
    sortOrder: 52,
    whatsIncluded: ["150+ edited photos", "Full event coverage", "Formal + candid shots", "Online gallery for all guests", "2 free 8x10 prints", "Delivery within 48h"],
    whatToBring: ["Event itinerary", "Key people list", "Venue details if off-site"],
    cancellationPolicy: "Free cancellation up to 48 hours before. 50% refund within 48 hours.",
  },
  // ── SPECIALTY ──
  {
    name: "Maternity Beach Session",
    slug: "maternity-beach-session",
    description: "Celebrate this magical chapter with a serene maternity session on the beach. Soft light, flowing fabrics, and tender moments between parents-to-be.",
    shortDescription: "Celebrate the bump. Serene maternity portraits on the beach.",
    category: "SPECIALTY",
    sessionType: "PORTRAIT",
    duration: 60,
    deliveredPhotos: 30,
    price: 79,
    depositAmount: 25,
    maxGroupSize: 4,
    isFeatured: false,
    sortOrder: 60,
    whatsIncluded: ["30+ edited photos", "Online gallery", "WhatsApp delivery within 24h", "1 free 8x10 print", "Posing guidance"],
    whatToBring: ["Flowing dress or draped fabric", "Partner outfit if joining", "Props (baby shoes, ultrasound)"],
    cancellationPolicy: "Free cancellation up to 24 hours before. Full refund for medical reasons at any time.",
  },
  {
    name: "Surprise Proposal",
    slug: "surprise-proposal",
    description: "We hide in plain sight and capture the moment your partner says yes. Pre-session planning call to coordinate timing, location, and signal. Then 60 minutes of celebration portraits.",
    shortDescription: "Hidden photographer captures the moment they say yes.",
    category: "SPECIALTY",
    sessionType: "CANDID",
    duration: 60,
    deliveredPhotos: 30,
    price: 129,
    depositAmount: 40,
    maxGroupSize: 2,
    isFeatured: true,
    sortOrder: 61,
    whatsIncluded: ["30+ edited photos", "Pre-session planning call", "Hidden photographer for the moment", "60 min celebration portraits after", "Rush delivery (12h)", "Online gallery"],
    whatToBring: ["The ring!", "Dressy outfit (partner too, subtly)", "Plan for afterwards (dinner reservation?)"],
    cancellationPolicy: "Free cancellation up to 48 hours before. 50% refund within 48 hours.",
  },
  {
    name: "Pets & Family",
    slug: "pets-and-family",
    description: "Your furry (or feathery) family members deserve to be in the photos too! We specialise in capturing the bond between families and their pets. Treats and patience included.",
    shortDescription: "Beautiful photos with your pets. Treats and patience included!",
    category: "SPECIALTY",
    sessionType: "CANDID",
    duration: 30,
    deliveredPhotos: 20,
    price: 49,
    depositAmount: null,
    maxGroupSize: 6,
    isFeatured: false,
    sortOrder: 62,
    whatsIncluded: ["20+ edited photos", "Pet + family portraits", "Candid play moments", "Online gallery", "WhatsApp delivery within 24h"],
    whatToBring: ["Pet's favourite treats and toys", "Lead/harness", "Water bowl", "Towel for sandy paws"],
    cancellationPolicy: "Free cancellation up to 24 hours before. No refund within 24 hours.",
  },
  {
    name: "Golden Hour Walking Tour",
    slug: "golden-hour-walking-tour",
    description: "A guided photo walk through the most photogenic spots during golden hour. Perfect for solo travellers, couples, or small groups who want beautiful photos and a local experience.",
    shortDescription: "Guided photo walk through the best spots at golden hour.",
    category: "SPECIALTY",
    sessionType: "MIXED",
    duration: 90,
    deliveredPhotos: 40,
    price: 99,
    depositAmount: 30,
    maxGroupSize: 4,
    isFeatured: false,
    sortOrder: 63,
    whatsIncluded: ["40+ edited photos", "Guided tour of best photo spots", "Local tips and recommendations", "Online gallery", "Multiple locations"],
    whatToBring: ["Comfortable walking shoes", "Water bottle", "Light layers for temperature changes"],
    cancellationPolicy: "Free cancellation up to 24 hours before. 50% refund within 24 hours.",
  },
];

async function main() {
  console.log("Seeding photo packages...");

  for (const pkg of PACKAGES) {
    const created = await prisma.photoPackage.upsert({
      where: { slug: pkg.slug },
      update: {
        name: pkg.name,
        description: pkg.description,
        shortDescription: pkg.shortDescription,
        category: pkg.category,
        sessionType: pkg.sessionType,
        duration: pkg.duration,
        deliveredPhotos: pkg.deliveredPhotos,
        price: pkg.price,
        depositAmount: pkg.depositAmount,
        maxGroupSize: pkg.maxGroupSize,
        isFeatured: pkg.isFeatured,
        sortOrder: pkg.sortOrder,
        whatsIncluded: pkg.whatsIncluded,
        whatToBring: pkg.whatToBring,
        cancellationPolicy: pkg.cancellationPolicy,
      },
      create: {
        name: pkg.name,
        slug: pkg.slug,
        description: pkg.description,
        shortDescription: pkg.shortDescription,
        category: pkg.category,
        sessionType: pkg.sessionType,
        duration: pkg.duration,
        deliveredPhotos: pkg.deliveredPhotos,
        price: pkg.price,
        depositAmount: pkg.depositAmount,
        currency: "EUR",
        maxGroupSize: pkg.maxGroupSize,
        isFeatured: pkg.isFeatured,
        sortOrder: pkg.sortOrder,
        whatsIncluded: pkg.whatsIncluded,
        whatToBring: pkg.whatToBring,
        cancellationPolicy: pkg.cancellationPolicy,
      },
    });

    // Upsert add-ons for this package
    const existing = await prisma.packageAddOn.findMany({ where: { packageId: created.id } });
    if (existing.length === 0) {
      await prisma.packageAddOn.createMany({
        data: ADD_ONS.map((a) => ({
          packageId: created.id,
          name: a.name,
          description: a.description,
          price: a.price,
          sortOrder: a.sortOrder,
        })),
      });
    }

    console.log(`  \u2713 ${pkg.name} (${pkg.category})`);
  }

  console.log(`\nSeeded ${PACKAGES.length} packages with ${ADD_ONS.length} add-ons each.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
