/**
 * Comprehensive expanded shop product seeder.
 *
 * Seeds 150+ ShopProduct rows covering every product category in the
 * Fotiqo / Fotiqo shop. Safe to re-run — uses upsert with
 * productKey as the unique key.
 *
 * Usage:
 *   npx tsx scripts/seed-products-expanded.ts
 *   DATABASE_URL=<url> npx tsx scripts/seed-products-expanded.ts
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// ── shared option sets ────────────────────────────────────────────────────────

const PRINT_FINISH_OPTIONS = [
  { key: "lustre",    label: "Lustre" },
  { key: "metallic",  label: "Metallic" },
  { key: "matte",     label: "Matte Velvet" },
  { key: "glossy",    label: "Glossy" },
  { key: "fineart",   label: "Fine Art Rag" },
  { key: "pearl",     label: "Pearl" },
];

const CANVAS_WRAP_OPTIONS = [
  { key: "gallery", label: "Gallery Wrap 1.5\"" },
  { key: "slim",    label: "Slim 0.75\"" },
  { key: "black",   label: "Black Edge" },
  { key: "white",   label: "White Edge" },
  { key: "mirror",  label: "Mirror Wrap" },
];

const METAL_FINISH_OPTIONS = [
  { key: "glossy",  label: "Glossy" },
  { key: "matte",   label: "Matte" },
  { key: "brushed", label: "Brushed" },
];

const FRAME_MAT_OPTIONS = [
  { key: "none",      label: "No Mat" },
  { key: "white_mat", label: "White Mat 5cm" },
  { key: "black_mat", label: "Black Mat 5cm" },
  { key: "cream_mat", label: "Cream Mat 5cm" },
];

const BOOK_COVER_OPTIONS = [
  { key: "photo",   label: "Photo Cover" },
  { key: "linen",   label: "Linen" },
  { key: "leather", label: "Leather" },
  { key: "silk",    label: "Silk" },
  { key: "velvet",  label: "Velvet" },
];

// ── type ──────────────────────────────────────────────────────────────────────

type Product = {
  productKey:      string;
  name:            string;
  description:     string;
  category:        string;
  subcategory?:    string;
  sizes?:          Array<{ key: string; label: string }>;
  defaultSize?:    string;
  options?:        Array<{ key: string; label: string }>;
  defaultOption?:  string;
  costPrice:       number;
  retailPrice:     number;
  fulfillmentType: string;
  labProductId?:   string;
  labName?:        string;
  isActive:        boolean;
  isFeatured:      boolean;
  sortOrder:       number;
  weight?:         number;
  shippingClass?:  string;
  turnaround?:     string;
};

// ── product catalogue ─────────────────────────────────────────────────────────

const PRODUCTS: Product[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // DIGITAL — 18 products
  // ══════════════════════════════════════════════════════════════════════════

  {
    productKey:      "single_photo",
    name:            "Single Photo Download",
    description:     "One full-resolution photo, completely watermark-free and ready to download instantly.",
    category:        "DIGITAL",
    costPrice:       0,
    retailPrice:     15,
    fulfillmentType: "DIGITAL",
    isActive:        true,
    isFeatured:      true,
    sortOrder:       1,
    turnaround:      "Instant",
  },
  {
    productKey:      "single_photo_hd",
    name:            "Single Photo HD (4K)",
    description:     "Maximum-resolution 4K export of one photo — perfect for large prints or TV slideshows.",
    category:        "DIGITAL",
    costPrice:       0,
    retailPrice:     22,
    fulfillmentType: "DIGITAL",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       2,
    turnaround:      "Instant",
  },
  {
    productKey:      "single_photo_web",
    name:            "Single Photo Web-Ready",
    description:     "Optimised web-resolution download, sized perfectly for sharing on social media.",
    category:        "DIGITAL",
    costPrice:       0,
    retailPrice:     5,
    fulfillmentType: "DIGITAL",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       3,
    turnaround:      "Instant",
  },
  {
    productKey:      "photo_pack_3",
    name:            "3 Photo Pack",
    description:     "Pick any three photos from your gallery — great value for a quick holiday keepsake.",
    category:        "DIGITAL",
    costPrice:       0,
    retailPrice:     35,
    fulfillmentType: "DIGITAL",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       4,
    turnaround:      "Instant",
  },
  {
    productKey:      "photo_pack_5",
    name:            "5 Photo Pack",
    description:     "Choose your five favourite shots from the session in full resolution.",
    category:        "DIGITAL",
    costPrice:       0,
    retailPrice:     50,
    fulfillmentType: "DIGITAL",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       5,
    turnaround:      "Instant",
  },
  {
    productKey:      "photo_pack_10",
    name:            "10 Photo Pack",
    description:     "Ten of your favourite shots downloaded instantly in high resolution.",
    category:        "DIGITAL",
    costPrice:       0,
    retailPrice:     75,
    fulfillmentType: "DIGITAL",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       6,
    turnaround:      "Instant",
  },
  {
    productKey:      "photo_pack_15",
    name:            "15 Photo Pack",
    description:     "Fifteen stunning shots from your session, delivered to your device in seconds.",
    category:        "DIGITAL",
    costPrice:       0,
    retailPrice:     90,
    fulfillmentType: "DIGITAL",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       7,
    turnaround:      "Instant",
  },
  {
    productKey:      "photo_pack_20",
    name:            "20 Photo Pack",
    description:     "Twenty beautifully captured moments from your holiday, all in full resolution.",
    category:        "DIGITAL",
    costPrice:       0,
    retailPrice:     105,
    fulfillmentType: "DIGITAL",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       8,
    turnaround:      "Instant",
  },
  {
    productKey:      "photo_pack_all",
    name:            "All Photos Pack",
    description:     "Every single photo from your session in one complete, watermark-free download.",
    category:        "DIGITAL",
    costPrice:       0,
    retailPrice:     130,
    fulfillmentType: "DIGITAL",
    isActive:        true,
    isFeatured:      true,
    sortOrder:       9,
    turnaround:      "Instant",
  },
  {
    productKey:      "full_gallery",
    name:            "Full Gallery Download",
    description:     "Your complete gallery unlocked — every photo, every memory, forever yours.",
    category:        "DIGITAL",
    costPrice:       0,
    retailPrice:     99,
    fulfillmentType: "DIGITAL",
    isActive:        true,
    isFeatured:      true,
    sortOrder:       10,
    turnaround:      "Instant",
  },
  {
    productKey:      "digital_pass_day",
    name:            "Day Pass",
    description:     "Unlimited photo downloads from a single day's session — pay once, keep everything.",
    category:        "DIGITAL",
    costPrice:       0,
    retailPrice:     49,
    fulfillmentType: "DIGITAL",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       11,
    turnaround:      "Instant",
  },
  {
    productKey:      "digital_pass_stay",
    name:            "Stay Pass",
    description:     "Unlimited photos and videos for your entire stay — the ultimate holiday memory package.",
    category:        "DIGITAL",
    costPrice:       0,
    retailPrice:     99,
    fulfillmentType: "DIGITAL",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       12,
    turnaround:      "Instant",
  },
  {
    productKey:      "digital_pass_vip",
    name:            "VIP Pass",
    description:     "Unlimited photos, priority photographer dispatch, and an exclusive sunset shoot included.",
    category:        "DIGITAL",
    costPrice:       0,
    retailPrice:     149,
    fulfillmentType: "DIGITAL",
    isActive:        true,
    isFeatured:      true,
    sortOrder:       13,
    turnaround:      "Instant",
  },
  {
    productKey:      "auto_reel",
    name:            "AI Video Reel",
    description:     "AI-edited highlight reel stitched from your best shots and set to royalty-free music.",
    category:        "DIGITAL",
    costPrice:       0,
    retailPrice:     25,
    fulfillmentType: "DIGITAL",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       14,
    turnaround:      "Instant",
  },
  {
    productKey:      "magic_shot",
    name:            "Magic Shot",
    description:     "An AR or 3D character effect seamlessly added to one of your holiday photos.",
    category:        "DIGITAL",
    costPrice:       0,
    retailPrice:     8,
    fulfillmentType: "DIGITAL",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       15,
    turnaround:      "Instant",
  },
  {
    productKey:      "digital_album_pdf",
    name:            "Digital Photo Album (PDF)",
    description:     "A beautifully designed PDF photo album you can share, print at home, or store forever.",
    category:        "DIGITAL",
    costPrice:       0,
    retailPrice:     15,
    fulfillmentType: "DIGITAL",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       16,
    turnaround:      "Instant",
  },
  {
    productKey:      "social_media_pack",
    name:            "Social Media Ready Pack",
    description:     "Your best shots pre-cropped and optimised for Instagram, Facebook, and TikTok.",
    category:        "DIGITAL",
    costPrice:       0,
    retailPrice:     22,
    fulfillmentType: "DIGITAL",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       17,
    turnaround:      "Instant",
  },
  {
    productKey:      "screensaver_pack",
    name:            "Wallpaper Pack (Phone + Desktop)",
    description:     "Holiday photos perfectly sized as lock screen and desktop wallpapers for all your devices.",
    category:        "DIGITAL",
    costPrice:       0,
    retailPrice:     8,
    fulfillmentType: "DIGITAL",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       18,
    turnaround:      "Instant",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // PRINT — 20 individual-size products
  // ══════════════════════════════════════════════════════════════════════════

  {
    productKey:      "print_wallet",
    name:            "Wallet Print 2.5×3.5\"",
    description:     "Classic wallet-size print — perfect for sharing with grandparents or slipping into a card.",
    category:        "PRINT",
    costPrice:       0.3,
    retailPrice:     3,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         PRINT_FINISH_OPTIONS,
    defaultOption:   "lustre",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       1,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "print_3x5",
    name:            "3×5 Print",
    description:     "A compact 3×5 lab-quality print on premium paper, ready to frame or display.",
    category:        "PRINT",
    costPrice:       0.4,
    retailPrice:     5,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         PRINT_FINISH_OPTIONS,
    defaultOption:   "lustre",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       2,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "print_4x6",
    name:            "4×6 Print",
    description:     "The most popular print size — vivid colour on lab-quality lustre, metallic, or matte paper.",
    category:        "PRINT",
    costPrice:       0.5,
    retailPrice:     6,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         PRINT_FINISH_OPTIONS,
    defaultOption:   "lustre",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       3,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "print_5x5",
    name:            "5×5 Square",
    description:     "A square 5×5 print — the ideal format for Instagram-style holiday shots.",
    category:        "PRINT",
    costPrice:       0.8,
    retailPrice:     8,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         PRINT_FINISH_OPTIONS,
    defaultOption:   "lustre",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       4,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "print_5x7",
    name:            "5×7 Print",
    description:     "A timeless 5×7 print that fits perfectly in most standard frames.",
    category:        "PRINT",
    costPrice:       1,
    retailPrice:     10,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         PRINT_FINISH_OPTIONS,
    defaultOption:   "lustre",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       5,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "print_6x6",
    name:            "6×6 Square",
    description:     "Bold square format that makes a statement on any shelf or desk.",
    category:        "PRINT",
    costPrice:       1,
    retailPrice:     10,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         PRINT_FINISH_OPTIONS,
    defaultOption:   "lustre",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       6,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "print_8x8",
    name:            "8×8 Square",
    description:     "A striking 8×8 square print that looks stunning in a simple box frame.",
    category:        "PRINT",
    costPrice:       1.5,
    retailPrice:     15,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         PRINT_FINISH_OPTIONS,
    defaultOption:   "lustre",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       7,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "print_8x10",
    name:            "8×10 Print",
    description:     "A classic 8×10 portrait print — the favourite for family photos and gift giving.",
    category:        "PRINT",
    costPrice:       2,
    retailPrice:     18,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         PRINT_FINISH_OPTIONS,
    defaultOption:   "lustre",
    isActive:        true,
    isFeatured:      true,
    sortOrder:       8,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "print_8x12",
    name:            "8×12 Print",
    description:     "A 8×12 panoramic-style print that preserves the full 3:2 camera ratio.",
    category:        "PRINT",
    costPrice:       2,
    retailPrice:     18,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         PRINT_FINISH_OPTIONS,
    defaultOption:   "lustre",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       9,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "print_10x10",
    name:            "10×10 Square",
    description:     "A generous square format that fills a wall with your favourite holiday memory.",
    category:        "PRINT",
    costPrice:       2.5,
    retailPrice:     22,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         PRINT_FINISH_OPTIONS,
    defaultOption:   "lustre",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       10,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "print_11x14",
    name:            "11×14 Print",
    description:     "An impressive 11×14 print that commands attention in any living room.",
    category:        "PRINT",
    costPrice:       3.5,
    retailPrice:     28,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         PRINT_FINISH_OPTIONS,
    defaultOption:   "lustre",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       11,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "print_12x12",
    name:            "12×12 Square",
    description:     "A large square print that pairs perfectly with a minimalist frame.",
    category:        "PRINT",
    costPrice:       3,
    retailPrice:     25,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         PRINT_FINISH_OPTIONS,
    defaultOption:   "lustre",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       12,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "print_12x18",
    name:            "12×18 Print",
    description:     "A 12×18 magazine-quality print — ideal as a statement piece or hallway photo.",
    category:        "PRINT",
    costPrice:       4,
    retailPrice:     32,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         PRINT_FINISH_OPTIONS,
    defaultOption:   "lustre",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       13,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "print_16x20",
    name:            "16×20 Print",
    description:     "A large-format 16×20 print that transforms any room into a gallery.",
    category:        "PRINT",
    costPrice:       5,
    retailPrice:     38,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         PRINT_FINISH_OPTIONS,
    defaultOption:   "lustre",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       14,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "print_16x24",
    name:            "16×24 Print",
    description:     "A stunning 16×24 large print that captures every detail of your holiday moment.",
    category:        "PRINT",
    costPrice:       5,
    retailPrice:     40,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         PRINT_FINISH_OPTIONS,
    defaultOption:   "lustre",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       15,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "print_20x24",
    name:            "20×24 Print",
    description:     "Premium 20×24 print — bold, vibrant, and impossible to miss on any wall.",
    category:        "PRINT",
    costPrice:       6,
    retailPrice:     45,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         PRINT_FINISH_OPTIONS,
    defaultOption:   "lustre",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       16,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "print_20x30",
    name:            "20×30 Poster",
    description:     "Cinema-quality 20×30 poster print — your favourite memory at exhibition scale.",
    category:        "PRINT",
    costPrice:       7,
    retailPrice:     52,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         PRINT_FINISH_OPTIONS,
    defaultOption:   "lustre",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       17,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "print_24x36",
    name:            "24×36 Large Poster",
    description:     "A dramatic 24×36 fine art poster — the largest standard print size we offer.",
    category:        "PRINT",
    costPrice:       9,
    retailPrice:     62,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         PRINT_FINISH_OPTIONS,
    defaultOption:   "lustre",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       18,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "print_a4",
    name:            "A4 Print",
    description:     "Standard A4 lab print — fits any off-the-shelf frame and looks beautiful.",
    category:        "PRINT",
    costPrice:       2,
    retailPrice:     18,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         PRINT_FINISH_OPTIONS,
    defaultOption:   "lustre",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       19,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "print_a3",
    name:            "A3 Print",
    description:     "A3 lab-quality print — double the impact of A4 in a single, stunning sheet.",
    category:        "PRINT",
    costPrice:       4,
    retailPrice:     32,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         PRINT_FINISH_OPTIONS,
    defaultOption:   "lustre",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       20,
    turnaround:      "3-5 business days",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // WALL_ART — canvas (15 products)
  // ══════════════════════════════════════════════════════════════════════════

  {
    productKey:      "canvas_20x20",
    name:            "Canvas 20×20cm",
    description:     "Compact square gallery-wrap canvas — great for collections or desk display.",
    category:        "WALL_ART",
    subcategory:     "canvas",
    costPrice:       10,
    retailPrice:     42,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         CANVAS_WRAP_OPTIONS,
    defaultOption:   "gallery",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       1,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "canvas_20x30",
    name:            "Canvas 20×30cm",
    description:     "Portrait-format canvas wrap that brings holiday photos to life on any wall.",
    category:        "WALL_ART",
    subcategory:     "canvas",
    costPrice:       12,
    retailPrice:     48,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         CANVAS_WRAP_OPTIONS,
    defaultOption:   "gallery",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       2,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "canvas_30x30",
    name:            "Canvas 30×30cm",
    description:     "A 30cm square canvas wrap — the perfect modern accent piece for any room.",
    category:        "WALL_ART",
    subcategory:     "canvas",
    costPrice:       14,
    retailPrice:     52,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         CANVAS_WRAP_OPTIONS,
    defaultOption:   "gallery",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       3,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "canvas_30x40",
    name:            "Canvas 30×40cm",
    description:     "Classic portrait canvas in our most popular holiday size — arrives ready to hang.",
    category:        "WALL_ART",
    subcategory:     "canvas",
    costPrice:       16,
    retailPrice:     58,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         CANVAS_WRAP_OPTIONS,
    defaultOption:   "gallery",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       4,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "canvas_30x45",
    name:            "Canvas 30×45cm",
    description:     "A 30×45 canvas that preserves the full 2:3 ratio of your original photo.",
    category:        "WALL_ART",
    subcategory:     "canvas",
    costPrice:       16,
    retailPrice:     62,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         CANVAS_WRAP_OPTIONS,
    defaultOption:   "gallery",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       5,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "canvas_40x40",
    name:            "Canvas 40×40cm",
    description:     "A bold square canvas that makes an instant focal point in any living space.",
    category:        "WALL_ART",
    subcategory:     "canvas",
    costPrice:       18,
    retailPrice:     68,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         CANVAS_WRAP_OPTIONS,
    defaultOption:   "gallery",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       6,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "canvas_40x60",
    name:            "Canvas 40×60cm",
    description:     "A striking 40×60 gallery-wrap canvas — one of our best-selling wall art sizes.",
    category:        "WALL_ART",
    subcategory:     "canvas",
    costPrice:       22,
    retailPrice:     78,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         CANVAS_WRAP_OPTIONS,
    defaultOption:   "gallery",
    isActive:        true,
    isFeatured:      true,
    sortOrder:       7,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "canvas_50x50",
    name:            "Canvas 50×50cm",
    description:     "A large square canvas — bold, modern, and guaranteed to impress guests.",
    category:        "WALL_ART",
    subcategory:     "canvas",
    costPrice:       22,
    retailPrice:     82,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         CANVAS_WRAP_OPTIONS,
    defaultOption:   "gallery",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       8,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "canvas_50x70",
    name:            "Canvas 50×70cm",
    description:     "A 50×70 statement canvas that turns your holiday photo into fine art.",
    category:        "WALL_ART",
    subcategory:     "canvas",
    costPrice:       28,
    retailPrice:     92,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         CANVAS_WRAP_OPTIONS,
    defaultOption:   "gallery",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       9,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "canvas_60x60",
    name:            "Canvas 60×60cm",
    description:     "An oversized square canvas — maximum impact in a minimalist format.",
    category:        "WALL_ART",
    subcategory:     "canvas",
    costPrice:       28,
    retailPrice:     95,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         CANVAS_WRAP_OPTIONS,
    defaultOption:   "gallery",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       10,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "canvas_60x80",
    name:            "Canvas 60×80cm",
    description:     "A large-format canvas print that fills your wall with holiday warmth.",
    category:        "WALL_ART",
    subcategory:     "canvas",
    costPrice:       32,
    retailPrice:     110,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         CANVAS_WRAP_OPTIONS,
    defaultOption:   "gallery",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       11,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "canvas_60x90",
    name:            "Canvas 60×90cm",
    description:     "A panoramic 60×90 canvas that transforms an entire wall into a memory.",
    category:        "WALL_ART",
    subcategory:     "canvas",
    costPrice:       35,
    retailPrice:     125,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         CANVAS_WRAP_OPTIONS,
    defaultOption:   "gallery",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       12,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "canvas_80x120",
    name:            "Canvas 80×120cm",
    description:     "Exhibition-scale canvas — your holiday photo printed at museum quality.",
    category:        "WALL_ART",
    subcategory:     "canvas",
    costPrice:       45,
    retailPrice:     155,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         CANVAS_WRAP_OPTIONS,
    defaultOption:   "gallery",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       13,
    shippingClass:   "OVERSIZED",
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "canvas_100x150",
    name:            "Canvas 100×150cm",
    description:     "A breathtaking 100×150 cm canvas — the ultimate statement piece for any home.",
    category:        "WALL_ART",
    subcategory:     "canvas",
    costPrice:       60,
    retailPrice:     210,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         CANVAS_WRAP_OPTIONS,
    defaultOption:   "gallery",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       14,
    shippingClass:   "OVERSIZED",
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "canvas_triptych",
    name:            "Canvas Triptych (3-panel)",
    description:     "A three-panel panoramic canvas set — your photo split across three canvases for a dramatic effect.",
    category:        "WALL_ART",
    subcategory:     "canvas",
    costPrice:       40,
    retailPrice:     135,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         CANVAS_WRAP_OPTIONS,
    defaultOption:   "gallery",
    isActive:        true,
    isFeatured:      true,
    sortOrder:       15,
    turnaround:      "3-5 business days",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // WALL_ART — metal (6 products)
  // ══════════════════════════════════════════════════════════════════════════

  {
    productKey:      "metal_20x30",
    name:            "Metal Print 20×30cm",
    description:     "Vibrant photo printed directly onto aluminium with rich, saturated colours.",
    category:        "WALL_ART",
    subcategory:     "metal",
    costPrice:       15,
    retailPrice:     42,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         METAL_FINISH_OPTIONS,
    defaultOption:   "glossy",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       1,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "metal_30x40",
    name:            "Metal Print 30×40cm",
    description:     "A 30×40 aluminium metal print that glows with depth and intensity.",
    category:        "WALL_ART",
    subcategory:     "metal",
    costPrice:       20,
    retailPrice:     58,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         METAL_FINISH_OPTIONS,
    defaultOption:   "glossy",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       2,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "metal_40x60",
    name:            "Metal Print 40×60cm",
    description:     "A bold 40×60 metal print — ultra-modern look with incredible colour accuracy.",
    category:        "WALL_ART",
    subcategory:     "metal",
    costPrice:       28,
    retailPrice:     78,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         METAL_FINISH_OPTIONS,
    defaultOption:   "glossy",
    isActive:        true,
    isFeatured:      true,
    sortOrder:       3,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "metal_50x70",
    name:            "Metal Print 50×70cm",
    description:     "Large-format metal print that brings unmatched luminosity to your holiday photo.",
    category:        "WALL_ART",
    subcategory:     "metal",
    costPrice:       35,
    retailPrice:     98,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         METAL_FINISH_OPTIONS,
    defaultOption:   "glossy",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       4,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "metal_60x80",
    name:            "Metal Print 60×80cm",
    description:     "An impressive 60×80 metal print — the showpiece finish for your most precious photo.",
    category:        "WALL_ART",
    subcategory:     "metal",
    costPrice:       40,
    retailPrice:     118,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         METAL_FINISH_OPTIONS,
    defaultOption:   "glossy",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       5,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "metal_60x90",
    name:            "Metal Print 60×90cm",
    description:     "The largest metal print in our collection — maximum drama, maximum colour.",
    category:        "WALL_ART",
    subcategory:     "metal",
    costPrice:       45,
    retailPrice:     145,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         METAL_FINISH_OPTIONS,
    defaultOption:   "glossy",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       6,
    shippingClass:   "OVERSIZED",
    turnaround:      "3-5 business days",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // WALL_ART — acrylic (5 products)
  // ══════════════════════════════════════════════════════════════════════════

  {
    productKey:      "acrylic_20x30",
    name:            "Acrylic Print 20×30cm",
    description:     "Photo printed under high-gloss acrylic for stunning depth and a premium floating appearance.",
    category:        "WALL_ART",
    subcategory:     "acrylic",
    costPrice:       18,
    retailPrice:     48,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       1,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "acrylic_30x40",
    name:            "Acrylic Print 30×40cm",
    description:     "A 30×40 acrylic print that pops with vivid colour and gallery-worthy depth.",
    category:        "WALL_ART",
    subcategory:     "acrylic",
    costPrice:       24,
    retailPrice:     65,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       2,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "acrylic_40x60",
    name:            "Acrylic Print 40×60cm",
    description:     "A large acrylic print that transforms your wall into a luxury art installation.",
    category:        "WALL_ART",
    subcategory:     "acrylic",
    costPrice:       32,
    retailPrice:     88,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      true,
    sortOrder:       3,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "acrylic_50x70",
    name:            "Acrylic Print 50×70cm",
    description:     "A 50×70 acrylic — spectacular colour depth that makes your holiday photo come alive.",
    category:        "WALL_ART",
    subcategory:     "acrylic",
    costPrice:       38,
    retailPrice:     110,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       4,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "acrylic_60x90",
    name:            "Acrylic Print 60×90cm",
    description:     "Our largest acrylic print — a breathtaking focal point for any premium interior.",
    category:        "WALL_ART",
    subcategory:     "acrylic",
    costPrice:       45,
    retailPrice:     140,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       5,
    shippingClass:   "OVERSIZED",
    turnaround:      "3-5 business days",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // WALL_ART — framed (12 products: 4 sizes × 3 frame colours)
  // ══════════════════════════════════════════════════════════════════════════

  {
    productKey:      "framed_black_20x30",
    name:            "Framed Print — Black 20×30cm",
    description:     "A 20×30 fine art print in a slim black frame, ready to hang straight from the box.",
    category:        "WALL_ART",
    subcategory:     "framed",
    costPrice:       14,
    retailPrice:     38,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         FRAME_MAT_OPTIONS,
    defaultOption:   "white_mat",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       1,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "framed_white_20x30",
    name:            "Framed Print — White 20×30cm",
    description:     "A 20×30 fine art print in a crisp white frame — perfect for bright, modern interiors.",
    category:        "WALL_ART",
    subcategory:     "framed",
    costPrice:       14,
    retailPrice:     38,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         FRAME_MAT_OPTIONS,
    defaultOption:   "white_mat",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       2,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "framed_wood_20x30",
    name:            "Framed Print — Natural Wood 20×30cm",
    description:     "A 20×30 fine art print in a warm natural wood frame for a Scandinavian aesthetic.",
    category:        "WALL_ART",
    subcategory:     "framed",
    costPrice:       16,
    retailPrice:     45,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         FRAME_MAT_OPTIONS,
    defaultOption:   "cream_mat",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       3,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "framed_black_30x40",
    name:            "Framed Print — Black 30×40cm",
    description:     "A 30×40 print in a classic black frame — the most popular framed size in our shop.",
    category:        "WALL_ART",
    subcategory:     "framed",
    costPrice:       18,
    retailPrice:     52,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         FRAME_MAT_OPTIONS,
    defaultOption:   "white_mat",
    isActive:        true,
    isFeatured:      true,
    sortOrder:       4,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "framed_white_30x40",
    name:            "Framed Print — White 30×40cm",
    description:     "A 30×40 print in a bright white frame that lets your photo take centre stage.",
    category:        "WALL_ART",
    subcategory:     "framed",
    costPrice:       18,
    retailPrice:     52,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         FRAME_MAT_OPTIONS,
    defaultOption:   "white_mat",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       5,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "framed_wood_30x40",
    name:            "Framed Print — Natural Wood 30×40cm",
    description:     "A warm 30×40 natural wood frame that adds a rustic, artisan touch to your space.",
    category:        "WALL_ART",
    subcategory:     "framed",
    costPrice:       20,
    retailPrice:     58,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         FRAME_MAT_OPTIONS,
    defaultOption:   "cream_mat",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       6,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "framed_black_40x60",
    name:            "Framed Print — Black 40×60cm",
    description:     "A statement 40×60 print in a sleek black gallery frame — museum quality at home.",
    category:        "WALL_ART",
    subcategory:     "framed",
    costPrice:       25,
    retailPrice:     72,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         FRAME_MAT_OPTIONS,
    defaultOption:   "white_mat",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       7,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "framed_white_40x60",
    name:            "Framed Print — White 40×60cm",
    description:     "A large 40×60 print in a clean white frame — elegant and timeless.",
    category:        "WALL_ART",
    subcategory:     "framed",
    costPrice:       25,
    retailPrice:     72,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         FRAME_MAT_OPTIONS,
    defaultOption:   "white_mat",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       8,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "framed_wood_40x60",
    name:            "Framed Print — Natural Wood 40×60cm",
    description:     "A large natural wood framed print that brings warmth and artistry to any room.",
    category:        "WALL_ART",
    subcategory:     "framed",
    costPrice:       28,
    retailPrice:     82,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         FRAME_MAT_OPTIONS,
    defaultOption:   "cream_mat",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       9,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "framed_black_50x70",
    name:            "Framed Print — Black 50×70cm",
    description:     "A dramatic 50×70 framed print in matte black — the definitive statement piece.",
    category:        "WALL_ART",
    subcategory:     "framed",
    costPrice:       30,
    retailPrice:     95,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         FRAME_MAT_OPTIONS,
    defaultOption:   "white_mat",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       10,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "framed_white_50x70",
    name:            "Framed Print — White 50×70cm",
    description:     "A large white framed print — bright, airy, and instantly elevates any interior.",
    category:        "WALL_ART",
    subcategory:     "framed",
    costPrice:       30,
    retailPrice:     95,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         FRAME_MAT_OPTIONS,
    defaultOption:   "white_mat",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       11,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "framed_wood_50x70",
    name:            "Framed Print — Natural Wood 50×70cm",
    description:     "A generous 50×70 in a handsome natural wood frame — the perfect gift for a special home.",
    category:        "WALL_ART",
    subcategory:     "framed",
    costPrice:       35,
    retailPrice:     135,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         FRAME_MAT_OPTIONS,
    defaultOption:   "cream_mat",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       12,
    turnaround:      "3-5 business days",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // SPECIALTY_WALL — 17 products
  // ══════════════════════════════════════════════════════════════════════════

  {
    productKey:      "wall_wood_30x40",
    name:            "Wood Print 30×40cm",
    description:     "Your photo printed directly onto real wood panels for a warm, textured look.",
    category:        "SPECIALTY_WALL",
    costPrice:       18,
    retailPrice:     52,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       1,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "wall_wood_40x60",
    name:            "Wood Print 40×60cm",
    description:     "A larger 40×60 wood print that showcases the beautiful natural grain alongside your photo.",
    category:        "SPECIALTY_WALL",
    costPrice:       25,
    retailPrice:     72,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       2,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "wall_bamboo_30x40",
    name:            "Bamboo Print 30×40cm",
    description:     "Eco-friendly photo print on sustainable bamboo board — beautiful and kind to the planet.",
    category:        "SPECIALTY_WALL",
    costPrice:       20,
    retailPrice:     55,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       3,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "wall_foam_30x40",
    name:            "Foam Board 30×40cm",
    description:     "Lightweight foam board print — ideal for temporary displays, events, or gifting.",
    category:        "SPECIALTY_WALL",
    costPrice:       8,
    retailPrice:     25,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       4,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "wall_foam_50x70",
    name:            "Foam Board 50×70cm",
    description:     "A large lightweight foam board print — perfect for photo-booth backdrops and displays.",
    category:        "SPECIALTY_WALL",
    costPrice:       15,
    retailPrice:     42,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       5,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "wall_dibond_30x40",
    name:            "Aluminum Dibond 30×40cm",
    description:     "Photo printed on rigid aluminium composite — ultra-flat, lightweight, and highly durable.",
    category:        "SPECIALTY_WALL",
    costPrice:       22,
    retailPrice:     62,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       6,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "wall_dibond_40x60",
    name:            "Aluminum Dibond 40×60cm",
    description:     "A premium 40×60 dibond panel — the professional photographer's choice for long-lasting display.",
    category:        "SPECIALTY_WALL",
    costPrice:       35,
    retailPrice:     88,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       7,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "wall_gallery_block_20x20",
    name:            "Gallery Block 20×20cm",
    description:     "A solid wood gallery block with your photo face-mounted — no frame needed.",
    category:        "SPECIALTY_WALL",
    costPrice:       12,
    retailPrice:     35,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       8,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "wall_gallery_block_30x30",
    name:            "Gallery Block 30×30cm",
    description:     "A 30×30 solid wood gallery block — a freestanding keepsake that doubles as wall art.",
    category:        "SPECIALTY_WALL",
    costPrice:       18,
    retailPrice:     48,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       9,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "wall_peel_stick_50x70",
    name:            "Peel & Stick Decal 50×70cm",
    description:     "Removable peel-and-stick wall decal — put it up, take it down, reposition with ease.",
    category:        "SPECIALTY_WALL",
    costPrice:       8,
    retailPrice:     25,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       10,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "wall_peel_stick_60x90",
    name:            "Peel & Stick Decal 60×90cm",
    description:     "A large 60×90 removable wall decal — bold, renter-friendly, and endlessly repositionable.",
    category:        "SPECIALTY_WALL",
    costPrice:       12,
    retailPrice:     35,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       11,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "wall_split_canvas_2",
    name:            "Split Canvas 2-Panel",
    description:     "Your photo artfully split across two matching canvases for a contemporary diptych effect.",
    category:        "SPECIALTY_WALL",
    costPrice:       25,
    retailPrice:     78,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       12,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "wall_split_canvas_3",
    name:            "Split Canvas 3-Panel",
    description:     "A stunning triptych split canvas — your holiday scene divided across three perfectly matched panels.",
    category:        "SPECIALTY_WALL",
    costPrice:       35,
    retailPrice:     110,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      true,
    sortOrder:       13,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "wall_split_canvas_4",
    name:            "Split Canvas 4-Panel",
    description:     "Four-panel split canvas — a dramatic quadriptych that fills an entire feature wall.",
    category:        "SPECIALTY_WALL",
    costPrice:       45,
    retailPrice:     145,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       14,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "wall_hexagon_set",
    name:            "Hexagon Photo Tiles (set of 7)",
    description:     "Seven hexagonal photo tiles that snap together into a customisable honeycomb gallery wall.",
    category:        "SPECIALTY_WALL",
    costPrice:       20,
    retailPrice:     62,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      true,
    sortOrder:       15,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "wall_circle_canvas",
    name:            "Circle Canvas 40cm",
    description:     "A unique circular canvas print — a fresh, modern take on traditional wall art.",
    category:        "SPECIALTY_WALL",
    costPrice:       18,
    retailPrice:     55,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       16,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "wall_heart_canvas",
    name:            "Heart Canvas 40cm",
    description:     "A heart-shaped canvas print — the perfect romantic gift to remember a special holiday together.",
    category:        "SPECIALTY_WALL",
    costPrice:       20,
    retailPrice:     58,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       17,
    turnaround:      "3-5 business days",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // PHOTO_BOOK — 12 products
  // ══════════════════════════════════════════════════════════════════════════

  {
    productKey:      "book_softcover_8x8_20pg",
    name:            "Softcover Photo Book 8×8\" (20 pages)",
    description:     "A compact 20-page softcover photo book — a quick and affordable holiday keepsake.",
    category:        "PHOTO_BOOK",
    costPrice:       8,
    retailPrice:     29,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         BOOK_COVER_OPTIONS,
    defaultOption:   "photo",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       1,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "book_softcover_10x10_20pg",
    name:            "Softcover Photo Book 10×10\" (20 pages)",
    description:     "A larger 10-inch softcover book — 20 pages of beautifully printed holiday memories.",
    category:        "PHOTO_BOOK",
    costPrice:       10,
    retailPrice:     35,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         BOOK_COVER_OPTIONS,
    defaultOption:   "photo",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       2,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "book_hardcover_8x8_20pg",
    name:            "Hardcover Photo Book 8×8\" (20 pages)",
    description:     "A premium hardcover photo book in a compact 8-inch square with 20 pages of memories.",
    category:        "PHOTO_BOOK",
    costPrice:       14,
    retailPrice:     48,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         BOOK_COVER_OPTIONS,
    defaultOption:   "linen",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       3,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "book_hardcover_10x10_20pg",
    name:            "Hardcover Photo Book 10×10\" (20 pages)",
    description:     "A beautiful 10-inch hardcover photo book — 20 pages of your favourite holiday shots.",
    category:        "PHOTO_BOOK",
    costPrice:       18,
    retailPrice:     58,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         BOOK_COVER_OPTIONS,
    defaultOption:   "linen",
    isActive:        true,
    isFeatured:      true,
    sortOrder:       4,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "book_hardcover_10x10_40pg",
    name:            "Hardcover Photo Book 10×10\" (40 pages)",
    description:     "Our most popular hardcover book — 40 pages to tell the full story of your holiday.",
    category:        "PHOTO_BOOK",
    costPrice:       24,
    retailPrice:     75,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         BOOK_COVER_OPTIONS,
    defaultOption:   "linen",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       5,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "book_hardcover_12x12_20pg",
    name:            "Hardcover Photo Book 12×12\" (20 pages)",
    description:     "A large-format 12-inch hardcover book — impressive presentation for any coffee table.",
    category:        "PHOTO_BOOK",
    costPrice:       22,
    retailPrice:     72,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         BOOK_COVER_OPTIONS,
    defaultOption:   "linen",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       6,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "book_hardcover_12x12_40pg",
    name:            "Hardcover Photo Book 12×12\" (40 pages)",
    description:     "Our premium 12-inch hardcover book with 40 pages — the ultimate holiday photo album.",
    category:        "PHOTO_BOOK",
    costPrice:       30,
    retailPrice:     95,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         BOOK_COVER_OPTIONS,
    defaultOption:   "linen",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       7,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "book_layflat_10x10_20pg",
    name:            "Layflat Album 10×10\" (20 pages)",
    description:     "Luxurious layflat binding — pages open completely flat for seamless two-page spreads.",
    category:        "PHOTO_BOOK",
    costPrice:       28,
    retailPrice:     89,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         BOOK_COVER_OPTIONS,
    defaultOption:   "leather",
    isActive:        true,
    isFeatured:      true,
    sortOrder:       8,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "book_layflat_10x10_40pg",
    name:            "Layflat Album 10×10\" (40 pages)",
    description:     "A 40-page layflat album with completely flat spreads — perfect for group holiday stories.",
    category:        "PHOTO_BOOK",
    costPrice:       38,
    retailPrice:     119,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         BOOK_COVER_OPTIONS,
    defaultOption:   "leather",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       9,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "book_layflat_12x12_20pg",
    name:            "Layflat Album 12×12\" (20 pages)",
    description:     "A 12-inch large-format layflat album — spectacular presentation for treasured family photos.",
    category:        "PHOTO_BOOK",
    costPrice:       38,
    retailPrice:     125,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         BOOK_COVER_OPTIONS,
    defaultOption:   "leather",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       10,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "book_layflat_12x12_40pg",
    name:            "Layflat Album 12×12\" (40 pages)",
    description:     "Our finest album — 40 flat-opening pages in a 12-inch format with a choice of luxury covers.",
    category:        "PHOTO_BOOK",
    costPrice:       52,
    retailPrice:     165,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options:         BOOK_COVER_OPTIONS,
    defaultOption:   "leather",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       11,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "book_mini_accordion",
    name:            "Mini Accordion Book",
    description:     "A compact accordion-fold keepsake book — pocket-sized and perfect as a handout gift.",
    category:        "PHOTO_BOOK",
    costPrice:       5,
    retailPrice:     19,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       12,
    turnaround:      "5-7 business days",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // GIFT — 25 products
  // ══════════════════════════════════════════════════════════════════════════

  // Drinkware (5)
  {
    productKey:      "gift_mug_classic",
    name:            "Photo Mug — Classic White",
    description:     "Start every morning with your favourite holiday memory on a dishwasher-safe ceramic mug.",
    category:        "GIFT",
    subcategory:     "drinkware",
    costPrice:       5,
    retailPrice:     18,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       1,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "gift_mug_magic",
    name:            "Photo Mug — Magic Colour-Change",
    description:     "A heat-activated magic mug — the photo appears when you pour your hot drink.",
    category:        "GIFT",
    subcategory:     "drinkware",
    costPrice:       7,
    retailPrice:     22,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      true,
    sortOrder:       2,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "gift_travel_mug",
    name:            "Photo Travel Mug",
    description:     "An insulated travel mug with your holiday photo — keep drinks hot or cold on the go.",
    category:        "GIFT",
    subcategory:     "drinkware",
    costPrice:       10,
    retailPrice:     28,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       3,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "gift_water_bottle",
    name:            "Photo Water Bottle",
    description:     "A BPA-free stainless steel water bottle personalised with your holiday photo.",
    category:        "GIFT",
    subcategory:     "drinkware",
    costPrice:       12,
    retailPrice:     32,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       4,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "gift_shot_glass_set",
    name:            "Photo Shot Glass Set (4)",
    description:     "Set of four photo shot glasses — a fun memento to share with friends after the holiday.",
    category:        "GIFT",
    subcategory:     "drinkware",
    costPrice:       8,
    retailPrice:     24,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       5,
    turnaround:      "5-7 business days",
  },

  // Home décor (5)
  {
    productKey:      "gift_cushion",
    name:            "Photo Cushion 40×40cm",
    description:     "Soft 40×40 cushion printed with your holiday memory — cosy and colourful.",
    category:        "GIFT",
    subcategory:     "home",
    costPrice:       8,
    retailPrice:     29,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       6,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "gift_blanket",
    name:            "Fleece Photo Blanket",
    description:     "Cosy full-bleed fleece blanket — wrap yourself in your best holiday photo.",
    category:        "GIFT",
    subcategory:     "home",
    costPrice:       18,
    retailPrice:     55,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       7,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "gift_towel",
    name:            "Photo Beach Towel",
    description:     "A bold beach towel printed full-bleed with your holiday photo — stand out at the pool.",
    category:        "GIFT",
    subcategory:     "home",
    costPrice:       15,
    retailPrice:     42,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       8,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "gift_calendar",
    name:            "Photo Calendar (12 month)",
    description:     "A 12-month personalised photo calendar — relive your holiday memories all year long.",
    category:        "GIFT",
    subcategory:     "home",
    costPrice:       8,
    retailPrice:     28,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       9,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "gift_mousepad",
    name:            "Photo Mousepad",
    description:     "Non-slip neoprene mousepad featuring your holiday photo — brighten your workspace.",
    category:        "GIFT",
    subcategory:     "home",
    costPrice:       3,
    retailPrice:     12,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       10,
    turnaround:      "5-7 business days",
  },

  // Tech (3)
  {
    productKey:      "gift_phone_case",
    name:            "Photo Phone Case",
    description:     "Slim, protective phone case with your holiday photo — choose your model at checkout.",
    category:        "GIFT",
    subcategory:     "tech",
    costPrice:       5,
    retailPrice:     22,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options: [
      { key: "iphone15",    label: "iPhone 15" },
      { key: "iphone16",    label: "iPhone 16" },
      { key: "samsung_s24", label: "Samsung S24" },
      { key: "samsung_s25", label: "Samsung S25" },
    ],
    defaultOption:   "iphone15",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       11,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "gift_laptop_sleeve",
    name:            "Photo Laptop Sleeve",
    description:     "Padded laptop sleeve printed with your holiday photo — protect your device in style.",
    category:        "GIFT",
    subcategory:     "tech",
    costPrice:       10,
    retailPrice:     32,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options: [
      { key: "13in", label: "13 inch" },
      { key: "15in", label: "15 inch" },
      { key: "16in", label: "16 inch" },
    ],
    defaultOption:   "15in",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       12,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "gift_tablet_case",
    name:            "Photo Tablet Case",
    description:     "Custom photo tablet case with fold-out stand — for iPad and Android tablets.",
    category:        "GIFT",
    subcategory:     "tech",
    costPrice:       12,
    retailPrice:     35,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       13,
    turnaround:      "5-7 business days",
  },

  // Bags (3)
  {
    productKey:      "gift_tote",
    name:            "Canvas Tote Bag",
    description:     "Reusable canvas tote bag printed with your holiday photo — eco-friendly and stylish.",
    category:        "GIFT",
    subcategory:     "bags",
    costPrice:       5,
    retailPrice:     19,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       14,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "gift_backpack",
    name:            "Photo Backpack",
    description:     "A practical photo backpack with a full-colour printed front panel.",
    category:        "GIFT",
    subcategory:     "bags",
    costPrice:       15,
    retailPrice:     45,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       15,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "gift_makeup_bag",
    name:            "Photo Makeup Bag",
    description:     "A personalised zip-up makeup bag — a beautiful and practical travel gift.",
    category:        "GIFT",
    subcategory:     "bags",
    costPrice:       6,
    retailPrice:     20,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       16,
    turnaround:      "5-7 business days",
  },

  // Games (2)
  {
    productKey:      "gift_puzzle_500",
    name:            "Photo Puzzle (500 pieces)",
    description:     "Turn your favourite holiday shot into a fun 500-piece jigsaw puzzle.",
    category:        "GIFT",
    subcategory:     "games",
    costPrice:       10,
    retailPrice:     35,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       17,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "gift_puzzle_1000",
    name:            "Photo Puzzle (1000 pieces)",
    description:     "A challenging 1000-piece puzzle made from your holiday photo — the perfect evening activity.",
    category:        "GIFT",
    subcategory:     "games",
    costPrice:       15,
    retailPrice:     48,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       18,
    turnaround:      "5-7 business days",
  },

  // Wearables (7)
  {
    productKey:      "gift_tshirt",
    name:            "Photo T-Shirt",
    description:     "Unisex cotton t-shirt with your holiday photo printed on the front.",
    category:        "GIFT",
    subcategory:     "wearables",
    costPrice:       8,
    retailPrice:     28,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options: [
      { key: "xs",  label: "XS" },
      { key: "s",   label: "S" },
      { key: "m",   label: "M" },
      { key: "l",   label: "L" },
      { key: "xl",  label: "XL" },
      { key: "xxl", label: "XXL" },
    ],
    defaultOption:   "m",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       19,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "gift_hoodie",
    name:            "Photo Hoodie",
    description:     "A premium pull-over hoodie with your holiday photo — warm memories for cool evenings.",
    category:        "GIFT",
    subcategory:     "wearables",
    costPrice:       18,
    retailPrice:     52,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options: [
      { key: "xs",  label: "XS" },
      { key: "s",   label: "S" },
      { key: "m",   label: "M" },
      { key: "l",   label: "L" },
      { key: "xl",  label: "XL" },
      { key: "xxl", label: "XXL" },
    ],
    defaultOption:   "m",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       20,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "gift_cap",
    name:            "Photo Cap",
    description:     "A classic embroidered or printed cap — your photo on the front panel.",
    category:        "GIFT",
    subcategory:     "wearables",
    costPrice:       7,
    retailPrice:     22,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       21,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "gift_apron",
    name:            "Photo Apron",
    description:     "A funny or heartfelt personalised photo apron — a brilliant gift for home cooks.",
    category:        "GIFT",
    subcategory:     "wearables",
    costPrice:       9,
    retailPrice:     28,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       22,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "gift_socks",
    name:            "Photo Socks",
    description:     "Custom socks with your holiday photo — novelty, fun, and always gets a laugh.",
    category:        "GIFT",
    subcategory:     "wearables",
    costPrice:       5,
    retailPrice:     16,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       23,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "gift_kids_tshirt",
    name:            "Kids Photo T-Shirt",
    description:     "Soft kids cotton t-shirt with your holiday photo — a souvenir they will actually wear.",
    category:        "GIFT",
    subcategory:     "wearables",
    costPrice:       7,
    retailPrice:     22,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    options: [
      { key: "3-4",   label: "Age 3-4" },
      { key: "5-6",   label: "Age 5-6" },
      { key: "7-8",   label: "Age 7-8" },
      { key: "9-11",  label: "Age 9-11" },
      { key: "12-14", label: "Age 12-14" },
    ],
    defaultOption:   "7-8",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       24,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "gift_pyjamas",
    name:            "Photo Pyjama Set",
    description:     "Comfortable photo pyjama set — go to sleep wrapped in your holiday memories.",
    category:        "GIFT",
    subcategory:     "wearables",
    costPrice:       15,
    retailPrice:     42,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       25,
    turnaround:      "5-7 business days",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // CARD — 10 products
  // ══════════════════════════════════════════════════════════════════════════

  {
    productKey:      "card_greeting_10",
    name:            "Greeting Cards (pack of 10)",
    description:     "Pack of 10 personalised greeting cards — your holiday photo on the front.",
    category:        "CARD",
    costPrice:       4,
    retailPrice:     18,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       1,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "card_greeting_25",
    name:            "Greeting Cards (pack of 25)",
    description:     "Pack of 25 personalised greeting cards — ideal for sharing your holiday news with everyone.",
    category:        "CARD",
    costPrice:       9,
    retailPrice:     38,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       2,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "card_postcard_5",
    name:            "Postcards (pack of 5)",
    description:     "Pack of 5 photo postcards printed on sturdy card — send a little piece of your holiday home.",
    category:        "CARD",
    costPrice:       2,
    retailPrice:     10,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       3,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "card_postcard_20",
    name:            "Postcards (pack of 20)",
    description:     "Pack of 20 photo postcards — send one to every friend and still have some left over.",
    category:        "CARD",
    costPrice:       7,
    retailPrice:     28,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       4,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "card_thank_you_10",
    name:            "Thank You Cards (pack of 10)",
    description:     "Personalised thank-you cards featuring your holiday photo — elegant and thoughtful.",
    category:        "CARD",
    costPrice:       4,
    retailPrice:     18,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       5,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "card_holiday_20",
    name:            "Holiday / Christmas Cards (pack of 20)",
    description:     "Pack of 20 seasonal photo cards — perfect for Christmas, New Year, or any celebration.",
    category:        "CARD",
    costPrice:       8,
    retailPrice:     30,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       6,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "card_birth_announcement",
    name:            "Birth Announcement Cards (pack of 20)",
    description:     "Announce your new arrival with a beautiful photo card — 20 cards with envelopes.",
    category:        "CARD",
    costPrice:       8,
    retailPrice:     30,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       7,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "card_save_the_date",
    name:            "Save the Date Cards (pack of 20)",
    description:     "Personalised save-the-date cards with your photo — start the celebration early.",
    category:        "CARD",
    costPrice:       8,
    retailPrice:     32,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       8,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "card_birthday_10",
    name:            "Birthday Cards (pack of 10)",
    description:     "Pack of 10 personalised birthday cards featuring your holiday photo — ready to send.",
    category:        "CARD",
    costPrice:       4,
    retailPrice:     18,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       9,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "card_folded_premium",
    name:            "Premium Folded Cards (pack of 10)",
    description:     "Thick 400gsm folded cards with a premium silk laminate finish — a truly luxury card.",
    category:        "CARD",
    costPrice:       7,
    retailPrice:     26,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       10,
    turnaround:      "3-5 business days",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // SOUVENIR — 15 products
  // ══════════════════════════════════════════════════════════════════════════

  {
    productKey:      "souvenir_usb",
    name:            "Waterproof Photo USB",
    description:     "Branded waterproof USB drive pre-loaded with all your high-resolution photos.",
    category:        "SOUVENIR",
    costPrice:       3,
    retailPrice:     28,
    fulfillmentType: "AUTO",
    isActive:        true,
    isFeatured:      true,
    sortOrder:       1,
    turnaround:      "2-3 business days",
  },
  {
    productKey:      "souvenir_magnet",
    name:            "Photo Fridge Magnet",
    description:     "A small but mighty fridge magnet with your holiday photo — a classic keepsake.",
    category:        "SOUVENIR",
    costPrice:       1.5,
    retailPrice:     10,
    fulfillmentType: "AUTO",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       2,
    turnaround:      "2-3 business days",
  },
  {
    productKey:      "souvenir_keychain",
    name:            "Photo Keychain",
    description:     "Keep your favourite holiday memory in your pocket with a photo keychain.",
    category:        "SOUVENIR",
    costPrice:       2,
    retailPrice:     10,
    fulfillmentType: "AUTO",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       3,
    turnaround:      "2-3 business days",
  },
  {
    productKey:      "souvenir_coaster_set",
    name:            "Photo Coaster Set (set of 4)",
    description:     "Set of four ceramic coasters, each with a different photo from your session.",
    category:        "SOUVENIR",
    costPrice:       5,
    retailPrice:     19,
    fulfillmentType: "AUTO",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       4,
    turnaround:      "2-3 business days",
  },
  {
    productKey:      "souvenir_ornament",
    name:            "Photo Ornament",
    description:     "A decorative photo ornament to hang and remember your holiday every day.",
    category:        "SOUVENIR",
    costPrice:       4,
    retailPrice:     15,
    fulfillmentType: "AUTO",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       5,
    turnaround:      "2-3 business days",
  },
  {
    productKey:      "souvenir_snowglobe",
    name:            "Photo Snow Globe",
    description:     "A magical snow globe with your holiday photo inside — shake it and watch the snow fall.",
    category:        "SOUVENIR",
    costPrice:       6,
    retailPrice:     25,
    fulfillmentType: "AUTO",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       6,
    turnaround:      "2-3 business days",
  },
  {
    productKey:      "souvenir_luggage_tag",
    name:            "Photo Luggage Tag",
    description:     "A sturdy photo luggage tag — spot your bag on the carousel instantly.",
    category:        "SOUVENIR",
    costPrice:       2,
    retailPrice:     8,
    fulfillmentType: "AUTO",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       7,
    turnaround:      "2-3 business days",
  },
  {
    productKey:      "souvenir_bottle_opener",
    name:            "Photo Bottle Opener",
    description:     "A pocket-sized metal bottle opener engraved or printed with your holiday photo.",
    category:        "SOUVENIR",
    costPrice:       2.5,
    retailPrice:     9,
    fulfillmentType: "AUTO",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       8,
    turnaround:      "2-3 business days",
  },
  {
    productKey:      "souvenir_bookmark",
    name:            "Photo Bookmark (set of 5)",
    description:     "Set of five laminated photo bookmarks — beautiful and practical for the whole family.",
    category:        "SOUVENIR",
    costPrice:       1.5,
    retailPrice:     7,
    fulfillmentType: "AUTO",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       9,
    turnaround:      "2-3 business days",
  },
  {
    productKey:      "souvenir_sticker_sheet",
    name:            "Photo Sticker Sheet",
    description:     "A sheet of die-cut photo stickers from your session — fun for kids and adults alike.",
    category:        "SOUVENIR",
    costPrice:       1,
    retailPrice:     6,
    fulfillmentType: "AUTO",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       10,
    turnaround:      "2-3 business days",
  },
  {
    productKey:      "souvenir_playing_cards",
    name:            "Custom Photo Playing Cards",
    description:     "A full deck of 54 playing cards, each with a different photo from your gallery.",
    category:        "SOUVENIR",
    costPrice:       8,
    retailPrice:     28,
    fulfillmentType: "AUTO",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       11,
    turnaround:      "2-3 business days",
  },
  {
    productKey:      "souvenir_photo_coin",
    name:            "Photo Coin / Token",
    description:     "A collectible metal photo coin engraved with your portrait — a unique holiday keepsake.",
    category:        "SOUVENIR",
    costPrice:       3,
    retailPrice:     12,
    fulfillmentType: "AUTO",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       12,
    turnaround:      "2-3 business days",
  },
  {
    productKey:      "souvenir_pin_badge",
    name:            "Photo Pin Badge",
    description:     "A glossy pin badge with your holiday photo — small, wearable, and full of personality.",
    category:        "SOUVENIR",
    costPrice:       1,
    retailPrice:     5,
    fulfillmentType: "AUTO",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       13,
    turnaround:      "2-3 business days",
  },
  {
    productKey:      "souvenir_mini_book",
    name:            "Pocket Photo Mini Book",
    description:     "A wallet-sized accordion mini book with your best six photos — perfect for grandparents.",
    category:        "SOUVENIR",
    costPrice:       2.5,
    retailPrice:     10,
    fulfillmentType: "AUTO",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       14,
    turnaround:      "2-3 business days",
  },
  {
    productKey:      "souvenir_frame_set",
    name:            "Instant Photo Frame Set (3 frames)",
    description:     "Set of three matching tabletop frames — pop your favourite prints in and display immediately.",
    category:        "SOUVENIR",
    costPrice:       6,
    retailPrice:     22,
    fulfillmentType: "AUTO",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       15,
    turnaround:      "2-3 business days",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BUNDLE — 8 products
  // ══════════════════════════════════════════════════════════════════════════

  {
    productKey:      "bundle_starter",
    name:            "Starter Bundle",
    description:     "The perfect introduction: digital download pack + 4×6 print + keychain — all in one.",
    category:        "BUNDLE",
    costPrice:       5,
    retailPrice:     35,
    fulfillmentType: "MANUAL",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       1,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "bundle_family",
    name:            "Family Bundle",
    description:     "Full gallery download + 8×10 print + photo book + two keychains — one for every member.",
    category:        "BUNDLE",
    costPrice:       35,
    retailPrice:     119,
    fulfillmentType: "MANUAL",
    isActive:        true,
    isFeatured:      true,
    sortOrder:       2,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "bundle_premium",
    name:            "Premium Bundle",
    description:     "Full gallery + AI video reel + 40×60 canvas + hardcover photo book — the complete package.",
    category:        "BUNDLE",
    costPrice:       65,
    retailPrice:     215,
    fulfillmentType: "MANUAL",
    isActive:        true,
    isFeatured:      true,
    sortOrder:       3,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "bundle_gift",
    name:            "Gift Bundle",
    description:     "5 photo pack + photo mug + cushion + greeting cards — a gorgeous ready-to-gift set.",
    category:        "BUNDLE",
    costPrice:       22,
    retailPrice:     75,
    fulfillmentType: "MANUAL",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       4,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "bundle_wall_gallery",
    name:            "Wall Gallery Bundle",
    description:     "Three coordinated framed prints in matching sizes — curated and ready to hang together.",
    category:        "BUNDLE",
    costPrice:       55,
    retailPrice:     165,
    fulfillmentType: "MANUAL",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       5,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "bundle_memory_box",
    name:            "Memory Box Bundle",
    description:     "A curated memory box: USB + prints + photo book + ornament — the complete holiday archive.",
    category:        "BUNDLE",
    costPrice:       45,
    retailPrice:     145,
    fulfillmentType: "MANUAL",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       6,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "bundle_honeymoon",
    name:            "Honeymoon Bundle",
    description:     "Full gallery + layflat album + canvas + champagne-glass ornaments — the romantic complete set.",
    category:        "BUNDLE",
    costPrice:       85,
    retailPrice:     275,
    fulfillmentType: "MANUAL",
    isActive:        true,
    isFeatured:      true,
    sortOrder:       7,
    turnaround:      "5-7 business days",
  },
  {
    productKey:      "bundle_splash",
    name:            "Splash Day Bundle",
    description:     "Day Pass + AI reel + two magic shots + beach towel — the perfect water park package.",
    category:        "BUNDLE",
    costPrice:       20,
    retailPrice:     79,
    fulfillmentType: "MANUAL",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       8,
    turnaround:      "5-7 business days",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // DISPLAY — 8 products
  // ══════════════════════════════════════════════════════════════════════════

  {
    productKey:      "display_easel_print",
    name:            "Easel-Back Print 5×7\"",
    description:     "A 5×7 print mounted on a sturdy easel-back board — freestanding and frame-free.",
    category:        "DISPLAY",
    costPrice:       3,
    retailPrice:     14,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       1,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "display_acrylic_block_s",
    name:            "Acrylic Photo Block — Small (10×10cm)",
    description:     "A solid acrylic block with your photo embedded inside — desk-worthy modern art.",
    category:        "DISPLAY",
    costPrice:       8,
    retailPrice:     28,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       2,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "display_acrylic_block_l",
    name:            "Acrylic Photo Block — Large (15×15cm)",
    description:     "A large solid acrylic block — your photo suspended in crystal-clear acrylic.",
    category:        "DISPLAY",
    costPrice:       14,
    retailPrice:     42,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       3,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "display_photo_stand",
    name:            "Tabletop Photo Stand (5×7\")",
    description:     "A slim metal tabletop stand with your 5×7 photo — minimal and elegant.",
    category:        "DISPLAY",
    costPrice:       4,
    retailPrice:     15,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       4,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "display_photo_cube",
    name:            "Photo Cube (6-sided)",
    description:     "A 6-sided photo cube displaying a different image on each face — a desktop conversation piece.",
    category:        "DISPLAY",
    costPrice:       8,
    retailPrice:     26,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       5,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "display_led_frame",
    name:            "LED Light-Up Photo Frame",
    description:     "A light-up LED frame that illuminates your photo from behind — stunning as a nightlight.",
    category:        "DISPLAY",
    costPrice:       15,
    retailPrice:     45,
    fulfillmentType: "AUTO",
    isActive:        true,
    isFeatured:      true,
    sortOrder:       6,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "display_floating_frame",
    name:            "Floating Acrylic Frame (20×30cm)",
    description:     "A borderless floating acrylic frame — your photo appears to hover on the wall.",
    category:        "DISPLAY",
    costPrice:       18,
    retailPrice:     52,
    fulfillmentType: "AUTO",
    labName:         "PRODIGI",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       7,
    turnaround:      "3-5 business days",
  },
  {
    productKey:      "display_magnetic_frame_set",
    name:            "Magnetic Fridge Frame Set (3 frames)",
    description:     "Set of three magnetic fridge frames — display your favourite prints right on the fridge.",
    category:        "DISPLAY",
    costPrice:       5,
    retailPrice:     18,
    fulfillmentType: "AUTO",
    isActive:        true,
    isFeatured:      false,
    sortOrder:       8,
    turnaround:      "3-5 business days",
  },

];

// ── seeder ────────────────────────────────────────────────────────────────────

async function main() {
  console.log("seeding expanded product catalogue…\n");

  const counts: Record<string, number> = {};
  let created = 0;

  for (const p of PRODUCTS) {
    await prisma.shopProduct.upsert({
      where: { productKey: p.productKey },
      update: {
        name:            p.name,
        retailPrice:     p.retailPrice,
        costPrice:       p.costPrice,
        isActive:        p.isActive,
        isFeatured:      p.isFeatured,
      },
      create: {
        productKey:      p.productKey,
        name:            p.name,
        description:     p.description,
        category:        p.category,
        subcategory:     p.subcategory    || null,
        sizes:           p.sizes          ? JSON.stringify(p.sizes)    : null,
        defaultSize:     p.defaultSize    || null,
        options:         p.options        ? JSON.stringify(p.options)  : null,
        defaultOption:   p.defaultOption  || null,
        costPrice:       p.costPrice,
        retailPrice:     p.retailPrice,
        fulfillmentType: p.fulfillmentType,
        labProductId:    p.labProductId   || null,
        labName:         p.labName        || null,
        isActive:        p.isActive,
        isFeatured:      p.isFeatured,
        sortOrder:       p.sortOrder,
        weight:          p.weight         || null,
        shippingClass:   p.shippingClass  || null,
        turnaround:      p.turnaround     || null,
      },
    });

    counts[p.category] = (counts[p.category] ?? 0) + 1;
    created++;
  }

  // ── per-category summary ──────────────────────────────────────────────────
  console.log("Products per category:");
  for (const [cat, count] of Object.entries(counts).sort()) {
    console.log(`  ${cat.padEnd(18)} ${count}`);
  }

  const featured = PRODUCTS.filter((p) => p.isFeatured).length;
  console.log(`\nSeeded ${created} products  (${featured} featured)`);

  await prisma.$disconnect();
}

main().catch((e) => {
  console.error("seed-products-expanded failed:", e);
  prisma.$disconnect();
  process.exit(1);
});
